### PR TITLE
Upgrade OwnCloud to 8.2.2 and update MD5 Hash

### PR DESCRIPTION
**Pull request by shakaran**

### CODE REVIEW

**Comment by aspdye** [comment]
:+1: for that. Would make it easier moving to 9.0 as discussed in #514

**Comment by shakaran** [comment]
:+1: for me if you want just put 9.0 instead :)

**Comment by JoshData** [comment]
Every time we upgrade OC I regret it....

**Comment by aspdye** [comment]
No Problems ... For me ;) ...ownCloud 8.2 is a stable release ... and it works fine ... with the current master.

**Comment by yodax** [comment]
This branch doesn't work for me, the hash needs to be: 8d99e81a52649bc4c2af0e438bdc02cf9d35877c

During the upgrade it mentions:

```
Disabled incompatible app: calendar
Disabled 3rd-party app: calendar
Disabled incompatible app: contacts
Disabled 3rd-party app: contacts
```

After the upgrade they do work.

**Comment by yodax** [comment]
If it is changed to:

```
diff --git a/setup/owncloud.sh b/setup/owncloud.sh
index c71c3ff..6871582 100755
--- a/setup/owncloud.sh
+++ b/setup/owncloud.sh
@@ -17,8 +17,8 @@ apt_install \
 apt-get purge -qq -y owncloud*
 
 # Install ownCloud from source of this version:
-owncloud_ver=8.1.1
-owncloud_hash=34077e78575a3e689825a00964ee37fbf83fbdda
+owncloud_ver=8.2.2
+owncloud_hash=8d99e81a52649bc4c2af0e438bdc02cf9d35877c
 
 # Migrate <= v0.10 setups that stored the ownCloud config.php in /usr/local rather than
 # in STORAGE_ROOT. Move the file to STORAGE_ROOT.
@@ -52,8 +52,8 @@ if [ ! -d /usr/local/lib/owncloud/ ] \
        # The two apps we actually want are not in ownCloud core. Clone them from
        # their github repositories.
        mkdir -p /usr/local/lib/owncloud/apps
-       git_clone https://github.com/owncloudarchive/contacts 4ff855e7c2075309041bead09fbb9eb7df678244 '' /usr/local/lib/owncloud/
-       git_clone https://github.com/owncloudarchive/calendar ec53139b144c0f842c33813305612e8006c42ea5 '' /usr/local/lib/owncloud/
+       git_clone https://github.com/owncloudarchive/contacts 9ba2e667ae8c7ea36d8c4a4c3413c374beb24b1b '' /usr/local/lib/owncloud/
+       git_clone https://github.com/owncloudarchive/calendar 2086e738a3b7b868ec59cd61f0f88b49c3f21dd1 '' /usr/local/lib/owncloud/
 
        # Fix weird permissions.
```

It also fixes https://github.com/mail-in-a-box/mailinabox/issues/761

**Comment by shakaran** [comment]
@yodax Thanks! Updated the PR with your change

**Comment by kurt89523** [comment]
Looks like this needs to be updated as well...

`git_clone https://github.com/owncloudarchive/contacts 9ba2e667ae8c7ea36d8c4a4c3413c374beb24b1b '' /usr/local/lib/owncloud/`
`git_clone https://github.com/owncloudarchive/contacts 9ba2e667ae8c7ea36d8c4a4c3413c374beb24b1b '' /usr/local/lib/owncloud/`

**Comment by JoshData** [comment]
If someone could open a new PR to update to ownCloud 8.2.3 plus the two add-ons as @kurt89523 noted, that'd be helpful.

**Comment by aspdye** [comment]
should be closed according to #789 :wink:

**Pull request closed without merging**
