### PR TITLE
Update zpush.sh to version 2.7.0

### PR DESCRIPTION
**Pull request by matidau**
Updated Z-Push repo that works with PHP8 and Mail-in-a-box

### CODE REVIEW

**Comment by jvolkenant** [comment]
I still find that my Inbox (which has 20k+ emails), disappears and needs to be resynced with a few different z-push php 8 branches I've tried, this branch included.

**Comment by matidau** [comment]
I thought we were almost home free. Do you mind grabbing your Z-Push log files and dropping them in this issue https://github.com/matidau/Z-Push/issues/3
`/var/log/z-push/z-push.log`
`/var/log/z-push/z-push-error.log`

and just in case the autodiscover logs
`/var/log/z-push/autodiscover.log`
`/var/log/z-push/autodiscover-error.log`

Also what device/s are you testing with? 

Appreciate you raising this and any testing you can help with.

**Comment by jvolkenant** [comment]
To report an update; Things have worked much better with matidau's changes 👍

**Comment by jvolkenant** [comment]
Your branch was working great for the last few weeks.  Trying 2.7.0.  I appreciate the work!

**Comment by JoshData** [comment]
So is everything OK with 2.7.0? Is this PR ok to merge?

**Comment by matidau** [comment]
I believe it is :)

**Comment by JoshData** [comment]
Thanks!

**Pull request merged**
