### PR TITLE
Make backups more configurable

### PR DESCRIPTION
**Pull request by ponychicken**
Backup location and maximum age can now be configured in the admin panel.
For now only S3 is supported, but adding other duplicity supported backends is easy now.

I had to change the way how backup_status works, as naively walking through the file system doesn't work when using a remote storage. It now queries  `duplicity collection-status` for the necessary info.

### CODE REVIEW

**Comment by JoshData** [comment]
Neat. Some things-

Your call to collection-status needs `"--archive-dir", backup_cache_dir,`, and it would be better if you can to collect the output without writing to a file using `check_output` instead of `check_call` and getting the output sent to stdout.

`max_age_in_days` may not be the right name. Full backups are held onto much longer than that because of increments. It's really a minimum age, sort of.

I don't think there's a need to check if `merged_config["max_age_in_days"]` is a string. I think we can assume that?

There are a few remaining `backup_dir`s still which can be deleted.

**Comment by JoshData** [comment]
Oh also per #228 can you add a config option to simply stop backups entirely?

And `target_type` is inferrable from `target`, right? Do we need a separate option for that?

**Comment by JoshData** [comment]
Sorry, some more....

To be RESTful, the daemon path should just be `/system/backup/config` for both the GET and the POST. You may need to then detect whether it's a GET or POST from code.

And in `setup/management.sh`, please add a comment about why we're installing some packages for Python 2 and not Python 3 like the rest of the management services.

**Comment by JoshData** [comment]
..... And we'd probably need some basic error handling in various places, since there are a lot of conditions in which these calls can fail now (remote host is down, password is incorrect, etc.). These errors shouldn't break the admin, for instance.

**Comment by ponychicken** [comment]
Thanks for reviewing.

I fixed all of your remarks, except:
* Error handling: It would probably best to keep some kind of log file of the backup success/error statuses, but I could use some help on how to catch the errors, my python knowledge is quite limited.
* On/Off: I'm not sure how to best implement the enable/disable switch as the cron job is currently created in the setup process.

**Comment by ponychicken** [comment]
I've added a proper error handling now, and the backup logs are viewable in the panel

**Comment by JoshData** [comment]
Hey thanks. I'm merging without your last two commits: without `--asynchronous-upload` because it's marked as experimental, and without logging because I don't want backup errors to go unnoticed in a log. If anything, we should email the administrator user when there's an error.

But there was still a lot of work to do to make this usable. For instance, if you had S3 selected, going back to a file location didn't work at all. Please look over my commits on master to see how my afternoon went merging this. :|

**Pull request closed without merging**
