### PR TITLE
allow for non-standard ssh port in status check

### PR DESCRIPTION
**Pull request by ianberinger**
Currently the ssh status check fails when ssh is running on a non-standard port.

### CODE REVIEW

**Comment by JoshData** [comment]
Hi,

Would you mind re-doing this to move `sshd -T 2>/dev/null | grep "^port " | sed "s/port //"` into status_checks.py, rather than storing it in the config file? Would be great as a new function `get_ssh_port`. You can safely shell sshd like this:

    output = shell('check_output', ['sshd', '-T'])

Also would be helpful to have the port number in the output when the check detects SSH isn't running, if it's not port 22.

Thanks.

**Comment by ianberinger** [comment]
Not at all. Should I put the get_ssh_port function in utils.py?

**Comment by JoshData** [comment]
It's unlikely to be used outside of status_checks, so I think in there.

**Comment by ianberinger** [comment]
That should do it.

**Comment by JoshData** [comment]
Thanks! I squashed the commits together and merged it in via 20d20df.

**Comment by ianberinger** [comment]
Thank you!

**Pull request closed without merging**
