### PR TITLE
Use the authoritative DNS server for PTR lookups

### PR DESCRIPTION
**Pull request by yodax**
For testing a possible solution to: https://github.com/mail-in-a-box/mailinabox/issues/628

This version will try to find the authoritative server for the address first and use that server to do the PTR lookup. After doing some reading on the matter I think this **might** solve the problem. It however doesn't happen al the time.

I would appreciate it if somebody could give this a try.

### CODE REVIEW

**Comment by yodax** [comment]
I have set up a 5 minute cron job on a test DO box to run this

```
#!/bin/bash
CURRLOG=/root/monitor.log
PREVLOG=/root/monitor.prev
touch "$CURRLOG"
touch "$PREVLOG"

mv "$CURRLOG" "$PREVLOG"

/root/mailinabox/management/status_checks.py --check-ptr > "$CURRLOG"
 
DIFF=$(diff "$CURRLOG" "$PREVLOG")
if [ ! -z "$DIFF" ]; then
	cat "$CURRLOG" | mail -s "Reverse DNS" michael@kroes.email
fi
```

This will mail me if the checks for the ptr record fail. Should give me a greater chance to reproduce the bug.

I did some digging into the Digital Ocean dns setup and it looks like they are use cloud fare, this change should land use at the proper DNS for the PTR records I think.

**Comment by soupdiver** [comment]
I deployed your branch.
How long should we wait until we consider it working?

**Comment by yodax** [comment]
Thanks for testing :smile:

The cronjob overnight showed that the problem isn't solved yet. The job run's every 5 minutes and I started it at 21:30 CET. It failed at:

- 1:00, with a not set
- 5:00, with a not set
- 6:00, with a not set
- 6:40, with a time out on ipv4
- 6:55, with a time out on ipv4 but not ipv6
- 7:00, with a time out on ipv6 but not ipv4

I think this shows the problem isn't querying the authoritative DNS server, I will add some logging to my branch and see if I can find the problem. 

I will close for now and reopen when I have something that will work

**Comment by soupdiver** [comment]
ah okay :santa:

**Pull request closed without merging**
