### PR TITLE
Upgrade to NextCloud 14

### PR DESCRIPTION
**Pull request by Gwerlas**
* Upgraded Nextcloud from 13.0.6 to 14.0.6.
* Upgraded Contacts from 2.1.5 to 2.1.8.
* Upgraded Calendar from 1.6.1 to 1.6.4.

### CODE REVIEW

**Comment by JoshData** [comment]
Thanks!

I'll merge after things settle down with everyone upgrading to v0.40.

**Comment by Gwerlas** [comment]
To test an upgrade from 12 to 14, I have to do a fresh install from v0.28, upgrade ubuntu to bionic64 and upgrade to mailinabox v0.40... but I guess this scenario isn't supported.

Perhaps I should trigger an error if Nextcloud is lower than 13 ?

**Comment by just4t** [comment]
@yodax @JoshData  As far as I know Nextcloud 15 deprecated 'the 'sendmail' option then, to setup SMTP looks it's a must ... How that should affect default (upgraded) nextcloud older versions to it, knowing there is no 'admin access' by default?

**Comment by JoshData** [comment]
We just need to set it https://github.com/mail-in-a-box/mailinabox/blob/master/setup/nextcloud.sh#L154 and and https://github.com/mail-in-a-box/mailinabox/blob/master/setup/nextcloud.sh#L208.

**Comment by yodax** [comment]
I saw a note in the changelog about enforcing 2fa in v15. That doesn’t make much sense in our case with CalDAV etc. I haven’t checked how they implemented it. But it wouldn’t be a great user experience if every user had to go and set app passwords for this. That would be worth investigating.

**Comment by just4t** [comment]
Yes! Plus added the option to create dedicated 'app passwords' to allow 'apps' and 'devices' (including the Nextcloud Sync app.) to access over the '2fa' if enabled, but I think must be setup as 'admin' inside 'nextcloud'

**Comment by JoshData** [comment]
Yup!

On January 15, 2019 2:45:37 PM EST, Yoann Colin <notifications@github.com> wrote:
>About the migration script, since an upgrade to v0.30 is mandatory
>before moving upward. I suggest to remove the code for Nextcloud 12 and
>prior versions.
>
>Are You OK with that ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mail-in-a-box/mailinabox/pull/1504#issuecomment-454525439

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by yodax** [comment]
Good catch on the storage path!

**Comment by JoshData** [comment]
I'm now testing this on my box and will merge in about a week if all goes well.

**Comment by yodax** [comment]
I've deployed this on my box too. Everything seems to work. However the server status messages show a warning about missing indexes. This can be solved by running: 

```sudo -u www-data php /usr/local/lib/owncloud/occ db:add-missing-indices```

I think we need to add this to the setup script. They didn't include this in the normal upgrade because it might take some time. I think we should include it.

I think [this location](https://github.com/mail-in-a-box/mailinabox/blob/master/setup/nextcloud.sh#L67) might work. Then we upgrade them every single time. Running the command again doesn't seem to be an issue.

**Comment by JoshData** [comment]
I get:

>     Missing index "share_with_index" in table "oc_share".
>    Missing index "parent_index" in table "oc_share".
>    Missing index "fs_mtime" in table "oc_filecache".

These probably aren't relevant to our main use cases, but it would be good to run the command --- good idea.

**Comment by yodax** [comment]
Hi thanks for picking this up so quickly 😃

Looking at it again I think the update index statement needs to go after the retry block. Definitely after the upgrade. Otherwise it doesn’t know that the indexes need updating. 

Sorry for the confusion.

**Comment by JoshData** [comment]
Thanks all!

**Pull request merged**
