### PR TITLE
Fixes #1437 -added virtualenv to be installed, some installs may not have this pac…

### LINKED ISSUE #1437: ubuntu_bionic branch intallation fails over VULTR 18.04 image
@JoshData Installed now 181007-1953 CEST the _ubuntu_bionic_ branch as fresh, over a VULTR 18.04 image and still reported issues remain at _installing mailinabox daemon_ step because the VULTR provided image doesn't built by default the _virtualenv_ and some or all of the following _python_ packages (I can't identify which ones are already in or not) then needed to install those packages to make the installation to end smoothly:
`apt-get install virtualenv`
`apt-get install python3 python-dev python3-dev`
`apt-get install build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev`
`apt-get install python-pip`
`apt-get install python-all-dev python-setuptools python-wheel`

- I think you should include them to be checked and if not in to call them to be installed, within the script if not we will get lots of support calls about, when not using the _DigitalOcean_ CLOUD server provider.

Hope this helps.

### PR DESCRIPTION
**Pull request by jvolkenant**
…kage preinstalled (vultr 18.04)

### CODE REVIEW

**Comment by jvolkenant** [comment]
Install log on a fresh 18.04 Vultr image

```
Primary Hostname: m.example.com
Public IP Address: ipv4
Public IPv6 Address: ipv6
Mail-in-a-Box Version:  v0.28-18-g032b5d8

Adding a swap file to the system...
Updating system packages...
Installing system packages...

                       urrent default time zone: 'US/Pacific'
Local time is now:      Wed Oct 24 08:24:36 PDT 2018.
Universal Time is now:  Wed Oct 24 15:24:36 UTC 2018.

Initializing system random number generator...
Creating SSH key for backup…
Firewall is active and enabled on system startup
Creating initial SSL certificate and perfect forward secrecy Diffie-Hellman parameters...
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
...truncated
Installing nsd (DNS server)...
Generating DNSSEC signing keys...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Creating new user database: /home/user-data/mail/users.sqlite
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
sudo: unable to resolve host m.example.com: Resource temporarily unavailable
Installing Nextcloud (contacts/calendar)...

Upgrading to Nextcloud version 13.0.5

sudo: unable to resolve host m.example.com: Resource temporarily unavailable
creating sqlite db
sudo: unable to resolve host m.example.com: Resource temporarily unavailable
Nextcloud is already latest version
Installing Z-Push (Exchange/ActiveSync server)...
Installing Mail-in-a-Box system management daemon...
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /usr/local/lib/mailinabox/env/bin/python3
Also creating executable in /usr/local/lib/mailinabox/env/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
Installing Munin (system monitoring)...
sudo: unable to resolve host m.example.com: Resource temporarily unavailable
updated DNS: m.example.com
web updated

Okay. I'm about to set up me@example.com for you. This account will also
have access to the box's control panel.
password: 
 (again): 
mail user added
updated DNS: example.com
web updated


-----------------------------------------------
Mail-in-a-Box uses Let's Encrypt to provision free SSL/TLS certificates
to enable HTTPS connections to your box. We're automatically
agreeing you to their subscriber agreement. See https://letsencrypt.org.

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Registering without email!

IMPORTANT NOTES:
 - Your account credentials have been saved in your Certbot
   configuration directory at /home/user-data/ssl/lets_encrypt. You
   should make a secure backup of this folder now. This configuration
   directory will also contain certificates and private keys obtained
   by Certbot so making regular backups of this folder is ideal.

-----------------------------------------------

Your Mail-in-a-Box is running.

Please log in to the control panel for further instructions at:

https://ipv4/admin

You will be alerted that the website has an invalid certificate. Check that
the certificate fingerprint matches:

09:75:E1:3C:B1:BA:19:B8:98:4D:9B:A4:7E:F2:36:31:A6:9D:E4:66:7B:DF:5A:17:10:F5:68:9D:2F:ED:8E:4C

Then you can confirm the security exception and continue.
```

**Comment by JoshData** [comment]
Thanks! I think we've been installing the wrong package for the last few months. I added `python-virtualenv` earlier this year but it should have been the one you added here, `virtualenv`. The comment a few lines above your change should be updated. And this can be applied to master since it's not really specific to Ubuntu 18.04.

**Comment by JoshData** [comment]
Interesting! Ok. So let's just drop python-virtualenv in this branch (and update the comment in the file).

**Comment by jvolkenant** [comment]
Updated that branch

**Comment by JoshData** [comment]
Thanks!!

**Pull request merged**
