### PR TITLE
Boredomdenied cipher patch

### PR DESCRIPTION
**Pull request by boredomdenied**
The new ciphers fail to send mail. 
Error is:
```
TLS handshaking: SSL_accept() failed: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
```

### CODE REVIEW

**Comment by stan3** [comment]
What's the client?

**Comment by boredomdenied** [comment]
Built-in email program for android phone.

**Comment by stan3** [comment]
Which android version?

**Comment by boredomdenied** [comment]
Email version: 4.1.83.3

**Comment by stan3** [comment]
Interesting, I have andriod version 7.1.2 and com.android.email app has the same version
as this in the app properties.  Which phone is this?

Also can't see easily from the diff, which cipher(s) did have to add?

**Comment by JoshData** [comment]
I'd also be curious to know if you can visit your box's static website or the /admin page in the browser on the phone, @boredomdenied.

**Pull request closed without merging**
