### PR TITLE
Apply SPF policy checks to incoming email

### PR DESCRIPTION
**Pull request by yodax**
I saw this on the forums or as an issue, but I can't find that anymore so I can't credit the original poster. 

This PR will apply SPF policy checking on incoming email. 

Policy SPF will check the if the sender has configured an SPF record on the domain.
This record contains the address of the smtp server(s) that is allowed to send email on behalf of this domain. If that doesn't match with the server sending us email, the message will be rejected.

This change should help fight spam. 

I have tested this with a fake mailer: https://emkei.cz. On a plain MIAB the message being send from this service will arrive once they get past postgrey. The from address I used has an SPF record on the domain.

After the changes the messages get bounced. The recipient is notified of the bounce and the reason why.

Message in /var/log/mail.log:
`Mar 16 18:43:25 box postfix/smtpd[15671]: NOQUEUE: reject: RCPT from emkei.cz[46.167.245.72]: 550 5.7.1 <DESTEMAIL>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=FROMMAIL;ip=46.167.245.72;r= DESTEMAIL; from=< FROMMAIL> to=< DESTEMAIL > proto=ESMTP helo=<emkei.cz>
Mar 16 18:43:25 box postfix/smtpd[15671]: disconnect from emkei.cz[46.167.245.72]`

The message the sender gets is: ```Recipient address rejected: Message rejected due to:
   SPF fail - not authorized. Please see
   http://www.openspf.net/Why?s=mfrom;id=**;ip=46.167.245.72;r=**```

Messages send with the authorized smtp server do arrive and so do messages without an spf record associated with the domain. 

Greylisting still works as well after the change.

### CODE REVIEW

**Comment by MeltedLux** [comment]
#698 is the original issue.

**Comment by yodax** [comment]
@MeltedLux thanks! Credit where credit is due: thanks @Firenzzz !

**Comment by JoshData** [comment]
Is there a not-so-hard way that we can test this in practice? e.g. How often will legitimate mail fail SPF? I don't know whether other mail servers typically actually reject SPF failures, because the false-positives used to be incredibly high (because forwarded mail without rewritten return-path addresses will fail SPF).

**Comment by yodax** [comment]
I'm running it since the pr on my mail server. Large chunk of my mail is still being forwarded by gmail, all of that will pass. 

I did get 2 rejected messages in the log. Both were valid rejections.

**Comment by yodax** [comment]
Could you share some stats/experience with us @Firenzzz?

**Comment by Firenzzz** [comment]
@yodax: I've grep'd logs on my box and from what it's worth (mostly notifications and conversations with another miab's) from 4th to 25th March I have never encountered any failed spfs, everything was "none" and "pass", but also never received any spam or impersonating mails. The only exception was in the beginning of March when I got a permerror on just one mail but very likely it was a valid rejection. I can only speculate due to a time gap but I think It's because an IP that was sending a mail was just not included in their spf, because right now they have 4 times "include:something", two specific IPs including one that has been rejected and a softfail in the end. My inbox consists of notifications from e.g. sites like github, digitalocean, letsencrypt, some other notifications, alerts from ossecs and conversations with colleagues. Before I started using miab I was also hosting my own setup with postfix, dovecot, etc etc and also can't recall any false positives. Despite that, unfortunately I don't think I can comment on a case @JoshData cited because that's very rare for me to forward anything to my miab box or got something forwarded from someone else, but from my experience an FP with postfix's spf checker be it perl or python is very rare. Since 1st March I've received about 250 mails, vast majority of them were notifications and alerts and among them only that one mail got discarded.

**Comment by yodax** [comment]
Thanks for you update!

I still haven't had any false positives, just two more righteous blocks. I don understand that this isn't a change you make lightly.

**Comment by ned14** [comment]
I patched in this PR into my own installation, but made it add a header saying whether it passed or failed rather than reject on connection and then configured a filter rule to send any failing or soft failing mail to a special folder. To date no mail except spam has been so tagged. I have about four mailing list subscriptions, all different sources and providers. Still waiting for someone to forward me an email however.

**Comment by yodax** [comment]
I was looking in to adding a marker and using spamassasin. That seems like a safer approach. I haven't had any blocks that weren't correct though. 

Do you have a patch for this?

**Comment by ned14** [comment]
@yodax If not a single mail gets misfiled after a month, I'll probably set it to refuse SPF failing mail on connection, but for now this is my config:

```
root@mail:/etc/postfix-policyd-spf-python# cat policyd-spf.conf
#  For a fully commented sample config file see policyd-spf.conf.commented

debugLevel = 1
defaultSeedOnly = 0

HELO_reject = SPF_Not_Pass
Mail_From_reject = Fail

PermError_reject = False
TempError_Defer = False

skip_addresses = 127.0.0.0/8,::ffff:127.0.0.0/104,::1,<your public IP here>
```

The email sent by github containing your comment was tagged thusly:
```
Received-SPF: Pass (sender SPF authorized) identity=mailfrom; client-ip=192.30.252.192; helo=github-smtp2a-ext-cp1-prd.iad.github.net; envelope-from=noreply@github.com; receiver=s_github@nedprod.com 
```

I have seen Fail and Softfail too, but only for spam. A surprising amount of Asian originating email is tagged None, so maybe they are less keen on SPF out there for some reason.

BTW in my previous hand rolled email box which ran for five years I had spamassassin sitting on the delivery refusal path as the final step after all other HELO filters (so after all the blackhole filters etc). That is regularly recommended against by almost all guides, but it worked well for me, it fell over frequently, but I had a cronjob restarting it every hour. You wouldn't want this on a server receiving a lot of email attempts, but I don't see more than a few attempts per second despite having my own email since 1996.

**Comment by ned14** [comment]
Another snippet which others may find useful is this:

```
root@mail:/etc/dovecot# cat sieve-spam.sieve
require ["regex", "fileinto", "imap4flags"];

if anyof (header :regex "Received-SPF" "^Fail", header :regex "Received-SPF" "^Softfail")
{
  fileinto "SPFfail";
  stop;
}

if allof (header :regex "X-Spam-Status" "^Yes") {
  fileinto "Spam";
  stop;
}
```

This send SPF failing mail to the SPFfail folder before all other email processing, including the mandatory Spam filtering rule. This guarantees you'll see the effects of turning on SPF fail on connection correctly.

**Comment by yodax** [comment]
I was looking in to the sieve filtering for this. I thought about moving it directly into the Spam folder on a fail. I do see some valid softfail's so I would probably leave those in the inbox.

@JoshData would you like that to be apart of this PR?

**Comment by ned14** [comment]
Filtering SPF failing email into Spam is redundant as Spamassassin already adds a hefty score to SPF failing email. Setting spamassassin's config to add a score of 5 for SPF fails would achieve the same result.

BTW I got my first non-spam SPF failed email. It was from a guy who had misconfigured his email server. He hadn't configured his DMARC with a policy of destroying SPF failing email, so I think us unilaterally doing so without checking DMARC is excessive.

If a domain owner misconfigures their SPF AND sets DMARC to say destroy all SPF failing email, then they should expect what they get. But without DMARC being checked I think it's overkill to destroy or reject all SPF failing email.

Also, FYI about 10% of the spam I receive fails its SPF. Auto SPF rejection is not as huge a win as running spamassassin during EHLO and rejecting the connection then.

**Comment by Firenzzz** [comment]
> because the false-positives used to be incredibly high (because forwarded mail without rewritten return-path addresses will fail SPF). 
@JoshData @yodax @ned14 I'd like to address that, as of today I turned on forwarding mails from outlook and iCloud (in addition to gmail) to my miab box and it seems that this issue is unfortunately valid. Mails from gmail and outlook are being forwarded as intended but from iCloud are not. It's worth noting that according to their headers Apple uses "(Oracle Communications Messaging Server 7.0.5.36.0 64bit (built Sep  8 2015))". Please note that message ids and unique mail addresses have been replaced.

```
Jun  3 22:29:23 mailinabox postfix/smtpd[11629]: connect from st13p17im-asmtp003.me.com[17.164.88.11]
Jun  3 22:29:25 mailinabox policyd-spf[11633]: None; identity=helo; client-ip=17.164.88.11; helo=st13p17im-asmtp003.me.com; envelope-from=noreply@facebookmail.com; receiver=xyz@xyz.me
Jun  3 22:29:25 mailinabox policyd-spf[11633]: Fail; identity=mailfrom; client-ip=17.164.88.11; helo=st13p17im-asmtp003.me.com; envelope-from=noreply@facebookmail.com; receiver=xyz@xyz.me
Jun  3 22:29:25 mailinabox postfix/smtpd[11629]: NOQUEUE: reject: RCPT from st13p17im-asmtp003.me.com[17.164.88.11]: 550 5.7.1 <xyz@xyz.me>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=noreply@facebookmail.com;ip=17.164.88.11;r=xyz@xyz.me
; from=<noreply@facebookmail.com> to=<xyz@xyz.me> proto=ESMTP helo=<st13p17im-asmtp003.me.com>
```

Because facebookmail.com spf is -all that basically means hardfail, but I happened to see softfails via an addon thunderbird called thundersec which gives me a red bar when it can see soft/hardfail/dkim fail/blacklisted ip in headers. How the same mail looks like when being forwarded from outlook:

```
Jun  3 22:36:43 mailinabox postfix/smtpd[12068]: connect from col004-omc3s16.hotmail.com[65.55.34.154]
Jun  3 22:36:44 mailinabox policyd-spf[12072]: None; identity=helo; client-ip=65.55.34.154; helo=col004-omc3s16.hotmail.com; envelope-from=xyz@outlook.com; receiver=xyz@xyz.me
Jun  3 22:36:45 mailinabox policyd-spf[12072]: Pass; identity=mailfrom; client-ip=65.55.34.154; helo=col004-omc3s16.hotmail.com; envelope-from=xyz@outlook.com; receiver=xyz@xyz.me
Jun  3 22:36:45 mailinabox postgrey[1800]: action=pass, reason=client whitelisted by dnswl.org (1/occasional spam), client_name=col004-omc3s16.hotmail.com, client_address=65.55.34.154, sender=xyz@outlook.com, recipient=xyz@xyz.me
Jun  3 22:36:45 mailinabox postfix/smtpd[12068]: 897247FA77: client=col004-omc3s16.hotmail.com[65.55.34.154]
Jun  3 22:36:46 mailinabox postfix/cleanup[12513]: 897247FA77: message-id=<f7fe114dc234n2b3mkafa5ad6318e089@www.facebook.com>
Jun  3 22:36:46 mailinabox opendkim[16018]: 897247FA77: s=s1024-2013-q3 d=facebookmail.com SSL
Jun  3 22:36:46 mailinabox opendmarc[1660]: 897247FA77 ignoring Authentication-Results at 0 from mail.xyz.me
Jun  3 22:36:46 mailinabox opendmarc[1660]: 897247FA77: facebookmail.com fail
Jun  3 22:36:46 mailinabox postfix/qmgr[5918]: 897247FA77: from=<xyz@outlook.com>, size=7642, nrcpt=1 (queue active)
Jun  3 22:36:46 mailinabox dovecot: lmtp(12515): Connect from 127.0.0.1
Jun  3 22:36:46 mailinabox spampd[8097]: processing message <f7fe114dc234n2b3mkafa5ad6318e089@www.facebook.com> for <xyz@xyz.me>
Jun  3 22:36:46 mailinabox postfix/smtpd[12068]: disconnect from col004-omc3s16.hotmail.com[65.55.34.154]
```

I'm not sure if that's the case but it appears that Oracle's mailserver sends only one X-Received (gmail sends two) and headers like X-Forwarded-To and X-Forwarded-For are missing when forwarded from Apple (present from gmail). On the other hand outlook sends headers Resent-Message-ID, Resent-To, Resent-Date and Resent-From and after probing each mailserver only mails from iCloud are being dismissed on spf grounds.

**Comment by ned14** [comment]
Been running over a month now. Just one false positive, and the guy had misconfigured his server.

I will say though SPF isn't hugely useful for spotting spam. 85% of my received spam passes SPF or has no SPF.

Ramping up the checks during postfix EHLO negotiate would seem a good idea. Spamassassin reports almost all of my spam fails some very easily checkable thing during EHLO. Here's an example:
```
X-Spam-Report: 
	*  1.3 RCVD_ILLEGAL_IP Received: contains illegal IP address
	*  0.9 RCVD_NUMERIC_HELO Received: contains an IP address used for HELO
	*  1.2 RCVD_HELO_IP_MISMATCH Received: HELO and IP do not match, but should
	*  2.7 RCVD_IN_PSBL RBL: Received via a relay in PSBL
	*      [104.145.87.201 listed in psbl.surriel.com]
	*  0.6 RCVD_IN_SORBS_WEB RBL: SORBS: sender is an abusable web server
	*      [104.145.87.201 listed in dnsbl.sorbs.net]
	*  1.3 RCVD_IN_RP_RNBL RBL: Relay in RNBL,
	*      https://senderscore.org/blacklistlookup/
	*      [104.145.87.201 listed in bl.score.senderscore.com]
	*  1.2 RCVD_IN_BL_SPAMCOP_NET RBL: Received via a relay in bl.spamcop.net
	*      [Blocked - see <http://www.spamcop.net/bl.shtml?104.145.87.201>]
	*  1.6 RCVD_IN_BRBL_LASTEXT RBL: No description available.
	*      [104.145.87.201 listed in bb.barracudacentral.org]
	*  2.0 PYZOR_CHECK Listed in Pyzor (http://pyzor.sf.net/)
	*  1.3 RDNS_NONE Delivered to internal network by a host with no rDNS
``` 
I can't see why mailinabox isn't checking more RBLs during EHLO. Anyone know why?

**Comment by yodax** [comment]
Thanks everybody for the constructive comments :smile: Looking at the posts above, shall I close this PR?

It might be good to focus on the comment of @ned14. If found [this](http://jimsun.linxnet.com/misc/postfix-anti-UCE.txt) post which details some of the configuration necessary.

**Comment by ned14** [comment]
@yodax I'm personally thinking SPF fail on EHLO would work great when combined with a whitelist of sources we definitely know will never, ever send SPF failing email. gmail, yahoomail, facebook etc are all good candidates. In a few years time buggy software which doesn't forward email correctly will get fixed and this can be turned on for everybody like the big email providers have done, but better I think to let the ecosystem clear itself up first before we do that here. Thoughts?

**Comment by yodax** [comment]
Since https://github.com/mail-in-a-box/mailinabox/pull/766 was merged about spamassin. My spam has gone down. 

This PR doesn't add to that. Thanks for the discussion though. I'm happy to revisit this in the future.

**Pull request closed without merging**
