### PR TITLE
I have changed the location we store the web-assets for the admin pages.

### PR DESCRIPTION
**Pull request by macmedia**
#1171 Updated the file to save the assets to /usr/local/mailinabox

### CODE REVIEW

**Comment by JoshData** [comment]
Hey. Thanks. But the alias should be only for the domains that the control panel is served on, so it should be here:

https://github.com/mail-in-a-box/mailinabox/blob/master/conf/nginx-primaryonly.conf#L4

and it should only serve the assets directory, not the whole /usr/local/mailinabox directory.

**Comment by macmedia** [comment]
Should we be storing this in `/usr/local/lib` rather then `/usr/local` to keep everything together?

```
/usr/local/lib/
├── mailinabox
├── owncloud
├── python2.7
├── python3.4
├── roundcubemail
└── z-push
```

**Comment by JoshData** [comment]
Good call. 

On May 22, 2017 1:21:42 PM EDT, Git Repository <notifications@github.com> wrote:
>Should we be storing this in `/usr/local/lib` rather then `/usr/local`
>to keep everything together?
>
>```
>/usr/local/lib/
>├── mailinabox
>├── owncloud
>├── python2.7
>├── python3.4
>├── roundcubemail
>└── z-push
>```
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/mail-in-a-box/mailinabox/pull/1179#issuecomment-303164997

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JoshData** [comment]
Great. Just confirm for me that you've tested this on a real box?

**Comment by macmedia** [comment]
I have tested this on the current master branch.

**Pull request merged**
