### PR TITLE
Add rcmcarddav plugin to roundcube mail for ownCloud contact access

### PR DESCRIPTION
**Pull request by brocktice**
These changes will pull and set up the rcmcarddav plugin for roundcube mail. The included scripts will automatically add an address book called 'ownCloud' that syncs with the user's owncCould contacts. This address book is NOT used by default, but it's easy for the user to change that in roundcube preferences if so desired.

Due to the database init of roundcube it's necessary to split the script, with a dbinit script running after everything else is done.

### CODE REVIEW

**Comment by JoshData** [comment]
Thanks! I'll review this as soon as I get a chance.

**Comment by JoshData** [comment]
You have:

> Work around bug in db init code in rcmcarddav

What was the bug?

Also, is there any way we can avoid calling composer and instead install additional packages via apt-get?

**Comment by brocktice** [comment]
I'm not sure where in the code the bug is. I dug into it a little but couldn't find it -- the key problem is that the database doesn't get initialized. When I can spare some more time I'll look again.

I don't really know how composer works but I do believe it can be installed as a system package instead, there's some mention of that over on the rcmcarddav github pages.

I understand if you want those resolved first. If anyone's more adept at PHP than I am please feel free to resolve it, as this is (IMO) a pretty critical bit of functionality for MIAB if you're using any mail client besides RCM.

**Comment by brocktice** [comment]
The way the composer install is currently done is per the documentation for the plugin, FWIW.

**Comment by brocktice** [comment]
I did some reading. Not all of the dependencies pulled in by composer are in the packaging system.

**Comment by brocktice** [comment]
Also, see https://github.com/blind-coder/rcmcarddav/issues/96 for the bug, hope to have it straightened out soon.

**Comment by brocktice** [comment]
DB bug found. Testing now, should be able to omit the second script if it's really fixed.

**Comment by brocktice** [comment]
OK this is on hold pending the PR to the rcmcarddav project.

**Comment by brocktice** [comment]
rcmcarddav has fixed the issue, waiting for merge of the issue_96 into mainline. This addresses the database bug. How should we approach composer?

**Comment by JoshData** [comment]
> How should we approach composer?

Don't know yet. Could you sort out which dependencies can be installed by apt-get and which can't?

**Comment by h8h** [comment]
Why do we need the composer and why do we need git clone?
If you read the 'master'-Branch INSTALL file: 
> If you are installing a git clone, [...] install the dependencies using composer

That means, if you're NOT installing a git clone you don't have to install the dependencies using composer.

So switch to tags
https://github.com/blind-coder/rcmcarddav/tags

Select the latest tag, read it's [INSTALL file](https://github.com/blind-coder/rcmcarddav/blob/922ee9495dc833a2de05380eacb930183e1145e9/INSTALL) and the composer gets never mentioned.

So in my opinion, we'll need the composer only if we're cloning the 'master' branch.

**Comment by JoshData** [comment]
That would make things easier!

**Comment by h8h** [comment]
Yep much easier, but the tags are somewhat outdated. This [commit](https://github.com/blind-coder/rcmcarddav/commit/bdf5e528a4ecf69a9cc1454793482ee836de11e1) is a very nice one. That makes things clearer.

**Comment by brocktice** [comment]
I can try to do that re: downloading the two packages manually and test.

**Comment by h8h** [comment]
that would be very nice ! thank you!

**Comment by PortableTech** [comment]
I was curious where this PR stood and if any assistance would be needed.

**Comment by ausminternet** [comment]
any News here?

**Comment by JoshData** [comment]
I would like to remove the dbinit step if at all possible, drop use of php composer by using a release package rather than git, and I'm not sure if we need to perform [step 1](https://github.com/blind-coder/rcmcarddav/blob/master/INSTALL) which is to log out all users.

**Comment by aspdye** [comment]
When will this be integrated?

**Comment by JoshData** [comment]
When someone submits a PR that addresses my points above.

**Comment by aspdye** [comment]
Dont know If this is still making sense according to #514

**Comment by bronson** [comment]
Until #514 is addressed (if ever), I think it makes sense to try to improve the ownCloud experience.  Josh's comment on 5 Sep 2015 sounds good.

It looks like composer installs two packages: httpful and vobject.  vobject has a Debian package, php-sabre-vobject, but httpful isn't packaged.

I suppose the alternatives are:
- have the setup script install the httpful phar
- package and put httpful in the mail-in-a-box ppa
- just inline it in the miab package (ha)
- use composer just for httpful
- ... anything else?

Not sure which one would be preferred.  The phar seems easiest, but that might just be beacuse I've never used phars.

phabricator just inlines it: https://packages.debian.org/sid/all/phabricator/filelist

**Comment by bronson** [comment]
Apparently CalDAV and CardDAV have been merged into core: https://lwn.net/Articles/671112/

So maybe this problem will just go away.

**Comment by cromulus** [comment]
How about using a [release tarball](https://github.com/blind-coder/rcmcarddav/releases) for rcmcarddav?

According to the official instructions [here](https://plugins.roundcube.net/packages/roundcube/carddav), it contains all of the necessary requirements and libs.

> Via release tarball:
Download and extract the release tarball into roundcube/plugins directory and rename the extracted directory to carddav. The tarball contains all necessary dependencies and does not need composer.

**Comment by JoshData** [comment]
Fixed by #1029 instead.

**Pull request closed without merging**
