### PR TITLE
add --replace-all argument to ssl_certificates.py

### PR DESCRIPTION
**Pull request by bronson**
I manually installed LE certs and didn't want to wait two months until I could try the letsencrypt branch.  Now, if you see `No domains hosted on this box need a certificate at this time.`, just run:

    ./management/ssl_certificates.py --replace-all

This is the simplest thing I saw that would work.  Happy to make changes or ignore in favor of a better solution.

LE worked great.  Love this branch.

### CODE REVIEW

**Comment by bronson** [comment]
Here are some notes I took while doing it:

    $ cd mailinabox
    $ sudo su

If you currently have certs that you care about, you can back them up:

    # cp -r /home/user-data/ssl ~/ssl-backup

The multiple checkouts here is to work around something strange about this repo's config.

    git fetch origin letsencrypt
    git checkout FETCH_HEAD
    git checkout -b letsencrypt
    setup/start.sh

If you haven't already configured an SSL cert, you should now be up and running with LE.  

If you have, then you'll see this in the output:

    No domains hosted on this box need a certificate at this time.

If you still want to install new certs, you can force them:

    ./management/ssl_certificates.py --replace-all

All done!  Enjoy your A+ SSL Labs report.


If you ever want to leave the letsencrypt branch, do this:

    git checkout v0.14
    git checkout -b master

And you're back on the latest release.

**Comment by bronson** [comment]
One more thing: what about printing a warning for non-DNS domains?  Now that I've looked at the code I see why that is, but I wouldn't have guessed.

**Comment by JoshData** [comment]
Does `--replace-all` have a use besides testing? Because you can also just move your existing certificates out of the ssl directory to see what would happen.

**Comment by bronson** [comment]
It has the use I used it for: overriding an installed, valid cert on a production system.

I was afraid of deleting the certs in the ssl dir...  Whenever I monkey with internals like that, software gets cranky.

If `rm -rf /home/user-data/ssl/*` is indeed the correct way to handle the situation then I guess it could be documented?

**Comment by bronson** [comment]
So, here's my question: what's the proper way to replace a valid cert?

**Comment by JoshData** [comment]
> So, here's my question: what's the proper way to replace a valid cert?

Delete the file, I guess.

I took care of this at https://github.com/mail-in-a-box/mailinabox/blob/master/management/ssl_certificates.py#L417 with

    management/ssl_certificates domain1 domain2 ...

or

    management/ssl_certificates --force

**Comment by bronson** [comment]
`management/ssl_certificates --force` looks great!

**Comment by sanderkwantes** [comment]
I just tried that (force) command, but i get an error (i tried the command after being able to provision via the web). Traceback message:
We have to wait 60 seconds for the certificate to be issued...
We have to wait 50 seconds for the certificate to be issued...
We have to wait 40 seconds for the certificate to be issued...
We have to wait 30 seconds for the certificate to be issued...
We have to wait 20 seconds for the certificate to be issued...
We have to wait 10 seconds for the certificate to be issued...
Traceback (most recent call last):
  File "./management/ssl_certificates.py", line 788, in <module>
    provision_certificates_cmdline()
  File "./management/ssl_certificates.py", line 436, in provision_certificates_cmdline
    status = provision_certificates(env, agree_to_tos_url=agree_to_tos_url, logger=my_logger, force_domains=force_domains, show_extended_problems=show_extended_problems)
  File "./management/ssl_certificates.py", line 323, in provision_certificates
    logger=my_logger)
  File "/usr/local/lib/python3.4/dist-packages/free_tls_certificates/client.py", line 137, in issue_certificate
    cert_response = client.request_issuance(csr, challgs)
  File "/usr/local/lib/python3.4/dist-packages/acme/client.py", line 310, in request_issuance
    headers={'Accept': content_type})
  File "/usr/local/lib/python3.4/dist-packages/acme/client.py", line 631, in post
    data = self._wrap_in_jws(obj, self._get_nonce(url))
  File "/usr/local/lib/python3.4/dist-packages/acme/client.py", line 508, in _wrap_in_jws
    jobj = obj.json_dumps().encode()
  File "/usr/local/lib/python3.4/dist-packages/acme/jose/interfaces.py", line 189, in json_dumps
    return json.dumps(self, default=self.json_dump_default, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.4/json/encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.4/json/encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.4/dist-packages/acme/jose/interfaces.py", line 214, in json_dump_default
    return python_object.to_partial_json()
  File "/usr/local/lib/python3.4/dist-packages/acme/jose/json_util.py", line 263, in to_partial_json
    return self.fields_to_partial_json()
  File "/usr/local/lib/python3.4/dist-packages/acme/jose/json_util.py", line 251, in fields_to_partial_json
    jobj[field.json_name] = field.encode(value)
  File "/usr/local/lib/python3.4/dist-packages/acme/jose/json_util.py", line 96, in encode
    return self.fenc(value)
  File "/usr/local/lib/python3.4/dist-packages/acme/jose/json_util.py", line 401, in encode_csr
    OpenSSL.crypto.FILETYPE_ASN1, csr.wrapped))
AttributeError: 'X509Req' object has no attribute 'wrapped'

**Comment by JoshData** [comment]
@sanderkwantes: Thanks yeah I see it too after upgrading the python modules...

**Comment by sanderkwantes** [comment]
I'm not sure but it might be something related to pyopenssl (python3-openssl:amd64 (0.13-2ubuntu6, automatic)), as current version is 0.13 (in ubuntu trusty). According to this issue letsencrypt is relying on v.0.15 of pyopenssl: https://github.com/letsencrypt/letsencrypt/issues/885.

**Comment by JoshData** [comment]
It's related but something else. A friend found the issue: https://github.com/mail-in-a-box/free_tls_certificates/commit/08323c54a328f72939761b924a8990a94e818547

I've just pushed an updated version of free_tls_certificates. If you re-run Mail-in-a-Box setup it'll grab the update, and then things should work. Let me know!

**Comment by sanderkwantes** [comment]
Yes! It works indeed right now. Thank you!

**Pull request closed without merging**
