### PR TITLE
Dark theme for Mail-in-a-Box

### PR DESCRIPTION
**Pull request by just4d**
Dark theme for MiaB is, at my side, a need because my eyes are, every day more, suffering with white / light backgrounds then, here you have my proposal ...

**DARK THEME - SCREENSHOT...**   [http://bit.ly/2SIiioL](http://bit.ly/2SIiioL)

**CUSTOMIZATIONS ...**

- Customized the template files: `index.html` and `check-status.html` and created/ added `custom.bootstrap.(min).css` files to override 'bootstrap' defaults for current 'light' theme.

- Patched the file: `setup/management.sh` to move my new custom files CSS (`custom.dark.boostrap.css`, `custom.dark.boostrap.min.css`) and IMAGES (white logo(s), white icon(s) ). This change must be considered TEMPORAL because surely @JoshData will finally wish to integrate provided files into his repository.

**HOW TO TEST IT ...**

`git clone -b master https://github.com/just4d/custom-dark.git && git clone -b dark_190304 https://github.com/just4d/mailinabox.git`

**NOTES ...**

_- Do never use it on 'production' servers. Everything here is being provided to make easy to the MiaB main developer to take the decision to merge or not this Pull Request into the mail-in-a-box ''master' and to consider the convenience to make it the default 'theme'._
- _Development server used for this job has been deleted and the development domain shown in the screenshot has been parked._

@JoshData Waiting your feedback :)

### CODE REVIEW

**Comment by jrsupplee** [comment]
`custom-dark.bootstrap(.min).css` files do not seem to be in the patch.

Why not implement this so that the user can choose between light and dark themes?

**Comment by just4t** [comment]
Tested again and worked whell at my side... !?

1) Try to run `git clone -b master https://github.com/just4d/custom-dark.git` once

- Check the files have been cloned at `/root/custom-dark/css/` folder ...
 and then (again, the first one):
 `git clone -b master https://github.com/just4d/custom-dark.git && git clone -b dark_190304 https://github.com/just4d/mailinabox.gi `

2) That shoud be the right way to go but coding it would be hard (even maintenace, afterwards) then, I don't think @JoshData would be open for that... Better to wait his answer/ opinion about that first.

**Comment by just4d** [comment]
Improved installation by merging in the custom 'dark theme'  CSS & PNG files management into `/setup(management.sh` file. Now to install it, works with:  `git clone -b dark_190304 https://github.com/just4d/mailinabox.git` , only.

**Comment by just4d** [comment]
This pull request is going to be closed now in favor of this new [Custom-Dark](https://github.com/just4t/custom-dark/blob/master/CHANGELOG.md) theme built as a standalone add-on for Mail-in-a-Box.

@jrsupplee As your requested, the new version, as standalone add-on, will allow you to apply the custom-dark theme and restore the default-light one at anytime...

- Please, test it ad your end and post [here](https://github.com/just4t/custom-dark/issues) is any issue arise at your end. 

In all cases, your comments about, are very important to make this new **Mail-in-a-Box** add-on to leave the current BETA level.

Waiting your feedback,

**Pull request closed without merging**
