### PR TITLE
Add tasks app to Nextcloud

### PR DESCRIPTION
**Pull request by jvolkenant**
It appears that z-push supports syncing tasks (but not notes unfortunately)

Using the Nextcloud Tasks app and Nine for Android, I'm able to view and edit tasks.

### CODE REVIEW

**Comment by yodax** [comment]
I know the project doesn't want to do feature creep, but I think this fits nicely with z-push 2.5. Change looks good. If @JoshData agrees on this PR I'll run a test with z-push and tasks.

**Comment by jvolkenant** [comment]
@yodax 

Very true. Due to how the logic works with setup/nextcloud.sh, apps are only installed on version upgrade.  So to test this you would have to either test with the Nextcloud 15.0.8 update PR or test manually (edit version.php).  I slated the version to be installed (0.10.1 for 15, vs 0.9.8 for 14)

**Comment by JoshData** [comment]
Yeah I'm not really inclined to enable more apps.

**Comment by yodax** [comment]
I think a case can be made to add this package; it relates to the typical "productivity" workflow. When you add an exchange connection under ios, This is one of the options you can select and it would be nice if that worked out of the box. 

Of course adding another moving part to the project increases the maintenance burden.

**Comment by jvolkenant** [comment]
Closing, it's understandable to keep keeping MIAB maintainable in its current form.

**Pull request closed without merging**
