### PR TITLE
Quota implementation

### PR DESCRIPTION
**Pull request by rainulf**
As solution for #58, I have a very simple quota implementation. :)

In terms of code, I kept the common structures & conventions as close as possible. But I do suggest some refactor and cleanups (eg. frontend) on maybe major releases. I followed a bunch of guides for dovecot quota, mainly these:
- http://wiki2.dovecot.org/Quota/Configuration
- https://sys4.de/en/blog/2013/04/08/postfix-dovecot-mailbox-quota/

The best implementation seems to be for dovecot to serve as service for postfix to avoid backscattering. The quota can probably be later be expanded to other mailboxes such as index, sent, etc or graces, but that's TBD.

I added a new column to `users` called `quota`, which contains `NUMERIC` that represents MB. It can probably be bytes, but I feel like MB is simpler and straightforward. Please suggest if otherwise.

I noticed that we already have `check_policy_service`  for `smtpd_recipient_restrictions`. I needed to add another one for quota, so I did, but I'm not sure if that's the way to do it (in terms of adding multiple entries of `check_policy_service`), so someone needs to verify that.

In any case, please review. Merge if like, close if not. I tested it on my own mail server and it seems to work OK.

### CODE REVIEW

**Comment by aspdye** [comment]
First: **Thank you for your PR** :rocket: 

There is an error: I cannot setup a mailinabox-instance with this branch. Setting up the first user gives the following output in command line:

Okay. I'm about to set up me@localhost.de for you. This account will also
have access to the box's control panel.
password:
 (again):
No quota provided.

FAILED: tools/mail.py user make-admin me@localhost.de
-----------------------------------------
That's not a user (me@localhost.de).
-----------------------------------------

Setting up an user manually is also not possible, because the installation script does not set the quota.

**Another Question**: How to set "unlimited" Quota? (0?)

**Comment by rainulf** [comment]
No problem!

I completely missed the first user on my test environment. It should be a straightforward fix by adding a quota parameter to `tools/mail.py`. I will do so as soon as I get the chance.

Yes, setting it 0 should set it unlimited or no quota. This PR includes roundcube integration :stuck_out_tongue_winking_eye: you should see its indicator at the left bottom side after you login.

**Comment by aspdye** [comment]
@JoshData Please review and merge :wink:

**Comment by pryley** [comment]
Yes please!!

**Comment by mrother** [comment]
@JoshData +1 

Thanks!

**Comment by aspdye** [comment]
@JoshData I know that your time is limited - but: Can you give us any statement why this PR is open for such a long time? Are there any problems or conflicts open? I think it is great work - and it works for me!

**Comment by JoshData** [comment]
Per-user quotas seem totally unnecessary to me. All users should just have the same quota, except maybe administrators, who should probably have no quota.

There's a lot going on in this PR, so I can't review it more carefully until I've closed the more important bugs.

**Comment by pryley** [comment]
I have a mailserver that manages multiple email accounts for over 10+ domains, some have 20+ users.

Having a default user quota with the ability to lower/raise for specific users would be very useful to have in order to give a higher quota on a case-by-case basis. I don't want to have to elevate a user to admin just to raise their quota.

Also for this many accounts, a quota is very important as otherwise some users tend to go wild. 

On the same note...

Feature request: **attachment size limit**.

**Comment by aspdye** [comment]
There is no "default" Quota. The default-option is "Unlimited". I think it is not complicated to set the Quota individual. Especial if you have "only" 20+ users. Let's talk again if you have 200+ :sweat_smile: 

The ability to define an attachment size limit is also an good function, but not integrated in Mail-in-a-Box. 
These and other "advanced" functions would be nice to have. :sweat: 
But unfortunately, I think it will never come - because of the following "policy":
> * Not make something customizable by power users.

**Comment by hadifarnoud** [comment]
His kind of managing all this in a dictatorship way. It's his way of doing things. I'd love Miab to have a better user management. as it is, it's good for a personal email server and nothing else.

on the contrary, something like Modoboa has the features you guys want. It's just, you may find it a bit harder to setup/config. I had issues with it.

Unfortunately, we can't do much until @JoshData wants to. nothing gets accepted.

**Comment by JoshData** [comment]
@hadifarnoud When you take over ensuring that all of the questions on the forum get answered and all of the security issues get reviewed and fixed, then you'll be welcome to merge all of the pull requests you want.

**Comment by hadifarnoud** [comment]
The narrow goal of miab makes it difficult to use for anything other than personal email server. you can get help from the community you know. it's what open source is all about. all these people are here to help

**Comment by JoshData** [comment]
> The narrow goal of miab makes it difficult to use for anything other than personal email server.

Look, all things equal, I would love for MiaB to be used everywhere -- not just for personal email. But I've tried to be very clear throughout that I'm not aiming for something with every feature that anyone might need. Narrow is good.

> all these people are here to help

People are helping. It's great. It makes me happy. But there are still a lot of questions on the forum and open issues (with higher priority than new features) that are waiting for me to look at. So long as that's the case, PRs for new features are going to wait.

**Comment by aspdye** [comment]
@hadifarnoud Maybe you want to know, what @JoshData posted on Twitter: https://twitter.com/JoshData/status/697054363550789633 :laughing: 

I think - we should open Mail-in-a-Box for more contributors (administrators,...). The problem, that only one person is looking after a project has broken many other open source projects too. 

Please do not take it personally @JoshData, that's really not meant against you. You've done great work ... but we should look after, that the work is great in the future.

**Comment by pryley** [comment]
@aspdye You misread me.

I have a mailinabox server that manages email accounts for 11 domains.
This is a total of 162 user emails.

**Comment by JoshData** [comment]
> I think - we should open Mail-in-a-Box for more contributors (administrators,...). The problem, that only one person is looking after a project has broken many other open source projects too.

You guys have it backwards --- administrators don't get to just do the fun stuff of building new features without taking on the responsibility of supporting the project when people have problems. Show me that I can go on vacation for a week and all of the support questions and bugs will be taken care of when I'm back!

**Comment by aspdye** [comment]
Sounds provocant - but: Let's try it :wink:

**Comment by pimpedoutgeek** [comment]
- For about 10 years I ran my own email server using man of the same components.
- Postfix was the least troublesome, dovecot was frequently logging errors and exceptions hard to fix and I gave up on Spamassassin for a DNS blacklist which worked well but proved to be a lot of maintenance.
- Eventually dovecot became unfixable after running it for 10 years and w/o the time and inclination to dig deep enough for a fix I luckily stumbledupon MIAB.
- As JoshData has plainly stated he has successfully put together an email server with the main components all from FOSS: Postfix, Dovecot, etc.
- My personal configuration used: Apache, Bind & DNS, shorewall and webmin to manage the blacklist, et. al.
- JoshData's component choices are superior to the components I used 10 years ago. And the part I welcomed more than anything is MIAB works out-of-the-box no fuss, no mess and has been since 5/2015. No downtime, no upgrade issues, no weird unfixable gotchas requiring many hours on a forum or ML searching for a fix. The only manual maintenance I do is running the bash perl script for SPAM and the sa-learn script for HAM. That's it and I enjoy SPAM free email w/o depending upon gmail.
- I only have a handful of users but could I use MIAB for a whole company into the hundreds or thousands?: I could.
- I for one and I suspect very many more if not the majority of MIAB users would be extremely disappointed if the admin and maintenance of MIAB went South even if for a minute.
- If somebody needs to build a better MIAB the components are there for thetaking. Like JoshData get the pieces put together with testing and pushed to github and TaDa! You will have your very won version of MIAB where you will be able to honor pull requests until the cows-come-home.

**Comment by aspdye** [comment]
@pryley Can you run Mail-in-a-Box with 162 users? :confused:

**Comment by pryley** [comment]
Well obviously. 11 domains with an average of 12 emails per domain. The only
problem I have is that I'm running short on HD space, so the mailbox and quota
features would be very appreciated.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1]
On Wed, Feb 10, 2016 at 8:25 a.m., aspdye <notifications@github.com> wrote:
@pryley [https://github.com/pryley] Can you run Mail-in-a-Box with 162 users?:confused: [https://assets-cdn.github.com/images/icons/emoji/unicode/1f615.png]

—
Reply to this email directly or view it on GitHub
[https://github.com/mail-in-a-box/mailinabox/pull/665#issuecomment-182460412] .[https://github.com/notifications/beacon/AAIPGyLxtbgeZJSSxzjomeK3E4Egfg-Qks5pi1v8gaJpZM4G_pOq.gif]

**Comment by aspdye** [comment]
I think wie should give Quota and options like attachment size - but tell the Admin: only customize if you know what you do ;)

**Comment by rainulf** [comment]
Sorry about the late reply as I have been very busy this past few weeks. First, thank you everyone who have shown interest with this PR.
Regarding quota implementation to mail-in-a-box, I believe this is where we draw the line between personal mailbox solution vs an enterprise one. The aim is clearly not the latter, but rather what describe in the README.md. Currently, it is already serving its purpose, so I do agree with @JoshData that this PR may not be needed - it will only add unnecessary noise and complexity to the project. It has all the necessary features, but it is also simple enough to be further customized by others.
I needed this feature for my own purpose, so I implemented it. I shared it with you guys in case others need it. Guys, it's not that complicated. Just cherry-pick if you need this, fork if you disagree with roadmap. Cheers~

**Comment by lazaros67** [comment]
I installed Miab  a few months ago. It works perfectly (i have about 10 email accounts on it).

I know that we all want more features, but we need to remeber that this software is something that JoshData provides for free.

So i would like to THANK JoshData for creating Miab and providing it to us.

**Comment by aspdye** [comment]
The question is: Makes Quota anything harder to maintain for @JoshData :question:

**Comment by lazaros67** [comment]
I dont know, because i am not familiar with writting code and creating software, 

But, since Miab is open source, anyone, who has the knowledge and free time, could add the quota feature, i think.

**Comment by hadifarnoud** [comment]
we want to help hence this pull request. the thing is, @JoshData wants to manage everything himself. If he allow others to pitch in, it wouldn't be so hard on him.

**Comment by JoshData** [comment]
Oh please. If you want to pitch in, start answering questions people are posting on the [forum](https://discourse.mailinabox.email/) (@aspdye does, thank you!). Find some issues labeled [documentation](https://github.com/mail-in-a-box/mailinabox/labels/documentation) and write some. Fix some of the [bugs](https://github.com/mail-in-a-box/mailinabox/issues?q=is%3Aissue+is%3Aopen+label%3Abug). When major security issues come to light, take on the responsibility for [promptly investigating whether they apply to Mail-in-a-Box](https://discourse.mailinabox.email/c/announcements). Test [release candidates](https://github.com/mail-in-a-box/mailinabox/issues/722). Double check the box's [security practices](https://github.com/mail-in-a-box/mailinabox/issues?q=is%3Aissue+is%3Aopen+label%3Asecurity). Write [automated tests](https://github.com/mail-in-a-box/mailinabox/tree/master/tests) to validate the box's functionality. Do not pretend like you know how to run this project better than I do until you've actually done the things I have to do to keep the project working.

Please, let's limit this thread to actual technical discussion of the changes in this pull request. If it continues to go off topic I will close & lock this thread.

**Pull request closed without merging**
