### PR TITLE
Added support of service selection

### PR DESCRIPTION
**Pull request by guyzmo**
cf #683 and #404 

- added checkboxes to disable web and/or dns on alias or user creation
- added ignore lists for domain not being handled on either web or dns
- added API for managing ignore lists

### CODE REVIEW

**Comment by guyzmo** [comment]
I believe the checkboxes I added in the templates can be rethought…

**Comment by guyzmo** [comment]
I have improved the UI for service selection, so it looks a bit nice and so the user can understand it. You'll find below screen captures to illustrate it. Per default, all services are set to be installed.

screen shot 2016-01-28 at 16 15 59

When you click on one service to disable it, then the following message is shown:

screen shot 2016-01-28 at 16 16 10

And here's how I've added it into the users page:

screen shot 2016-01-28 at 16 16 34

**Comment by JoshData** [comment]
This needs to be rethought-

* Services are a property of domains, not aliases, so the configuration should be in a new place for domains.
* I'm not sure what it really means to not provide web. If the DNS A record points at the box, the box has to respond with something when there's a web request. What does it respond with if web is marked as disabled? 
* There's no sense in disabling mail. If there are users/aliases for the domain, it obviously is supposed to handle mail. If there are no users/aliases, then what is there to disable?

**Comment by guyzmo** [comment]
> There's no sense in disabling mail. If there are users/aliases for the domain, it obviously is supposed to handle mail. If there are no users/aliases, then what is there to disable?

well, I added mail just FTW, it's a disabled button, and its state has no meaning. The thinking was that it would help make clear what the services are by listing them (including mail) even though mail cannot be switched off. I'm happy to remove it.

> Services are a property of domains, not aliases, so the configuration should be in a new place for domains.

Here the idea is to make it possible to add an alias (or an user) without adding the "full service package", so when you add an alias from a new unmanaged domain, that domain gets DNS and/or WWW or neither, depending on your choices.

Then, I agree with the concept of "services" being property of domains, but the MIAB interface does not implement such a concept. As part of a redesign of the UI, I guess it'd be nice to have a domain oriented user interaction, centered around domains. Meanwhile, I believe this implementation should be fine.

> I'm not sure what it really means to not provide web. If the DNS A record points at the box, the box has to respond with something when there's a web request. What does it respond with if web is marked as disabled?

There's no obligation to provide a WWW configuration for a domain. If you configure an A record to point at the box, but you do not want to serve any specific web content to the user, you can skip that domain's configuration and use the default catch-all domain.

**Comment by itslukej** [comment]
> I'm not sure what it really means to not provide web. If the DNS A record points at the box, the box has to respond with something when there's a web request. What does it respond with if web is marked as disabled?

The user may not want to have their website hosted at the mail server (like me). If web is marked as disabled, www and @ would have no dns record..

**Comment by JoshData** [comment]
> @ would have no dns record

That could result in mail not being accepted. (The box itself won't accept mail from domains without A records, iirc.)

**Comment by JoshData** [comment]
Also, if there's no DNS record, then it doesn't matter whether or not the box serves a website for that domain name.

**Comment by itslukej** [comment]
@JoshData If the user chooses not to have a A/AAAA record for @, then it should have a notice saying mail will not be accepted (or just have the box point to some blank page if nothing is set)

**Comment by guyzmo** [comment]
well, having no website on the MIAB server does not mean you're not configuring `@` and `www` to point to another server, which is totally possible with current MIAB configuration, and then the mail will work.

I'm currently only using MIAB for mail+DNS handling, web stuff is hosted on other VM and it works well — even though I'm doing a few hacks to work around the limitations of the GUI, which is the reason of this PR.

Also, I really doubt that an `A` record on `@` is *necessary* for a domain to receive mail, as long as the `MX` are properly defined (with an `A` record to where the `MX` points to) and all the associated SPF/DKIM lines are well setup. Mail servers don't really care about the other `A` records (including `@`).

**Comment by guyzmo** [comment]
BTW, unchecking DNS for a domain wouldn't mean that the domain's DNS is not managed, just that it is not managed by MIAB. I'm hosting DNS for other people who want to keep control of their domain's zone (by managing it through the DNS provider's interface page), but ask me to host only their mail.

Of course, it's then up to them to configure properly all the SPF/DKIM stuff so it works fine, but that's then not my problem ☺

**Comment by itslukej** [comment]
> I'm currently only using MIAB for mail+DNS handling, web stuff is hosted on other VM and it works well — even though I'm doing a few hacks to work around the limitations of the GUI, which is the reason of this PR.

This is exactly why I would like to see this merged

**Comment by bronson** [comment]
So, if I'm understanding correctly, the DNS button is identical to #404?  And the Mail button is identical to just not creating any addresses in that domain?

I remember people claiming that an MX record without an A record was an indicator of spamming.  However, I've been running rinspin.com that way for years without any adverse effects that I can tell...  maybe it's not a thing after all.

**Comment by guyzmo** [comment]
What I did is to make it possible for MIAB to setup a mail *without* doing anything on the DNS side. IIRC (because that patch has some dust on it), I made all DNS check ignored when the DNS box has been unchecked, maybe it would be smart to mark them as external and do check on those as well…

**Comment by JoshData** [comment]
Folks, I'm closing this PR for the reasons I noted earlier. @guyzmo: It was a good attempt, I appreciate the work that went into it. But we need another path.

To the extent the original problem is about the status checks, the solution is going to be about the status checks too.

**Comment by guyzmo** [comment]
@JoshData Iet me disagree on that, the issue is only partially about the checks, it's also about being able to fit other uses. As I said, you sometimes need to handle mail for DNS setup outside of MIAB, or handle DNS with mail outside of MIAB, or even have only Web with DNS and Mail somewhere else.

On my own setup, I am **never** using the web setup MIAB is doing, because I setup all the `A` names to other servers (I got a bunch of VMs and public IPv4s). So setting up the webserver with those is just cluttering the configuration for no use.

IMHO, DNS is a much more important issue, because of the way it's designed, when MIAB sets up DNS locally, whereas it's publicly setup elsewhere, then  the server managed by MIAB will shadow the real zone, and it might lead to all sorts of issues (like a broken MTA setup).

And finally, there's a use case for using the neat facility that MIAB offers to create DNS (because creating fully featured signed DNS manually definitely is a pain), without actually using Mail (or Web) features.

So where I might agree is that the solution I've implemented is not necessarily the best UX, but it's offering a way without doing a big UI refactoring in MIAB. I believe that the best way would to have some sort of wizard asking you what you want to add, and enable the right features matching the user's needs.

All in all, it's going way beyond simple status checks, it's also about avoiding double configuration of things, once in MIAB and once externally, where it might lead to conflicts, shadowing and unexpected behaviors of all sorts.

**Comment by JoshData** [comment]
> So setting up the webserver with those is just cluttering the configuration for no use.

A user-level option whose effect is only to make the configuration files prettier?

>  the server managed by MIAB will shadow the real zone, and it might lead to all sorts of issues (like a broken MTA setup)

Don't make up hypothetical problems, please. If you think there's an issue, try to produce the problem first.

> the neat facility that MIAB offers to create DNS (because creating fully featured signed DNS manually definitely is a pain), without actually using Mail (or Web) features

That's not working in this PR anyway, you said.

**Comment by guyzmo** [comment]
> A user-level option whose effect is only to make the configuration files prettier?
> Don't make up hypothetical problems, please. If you think there's an issue, try to produce the problem first.

Well, about the configuration find "clutter", it's a basic security principle for anything that has public Internet reach : if you don't need it, don't enable it. 

Because I'm keeping my production install in line with the stable releases, I got a bunch of hacks to apply at each update to:

- enable a few custom DNS-only zones,
- disable serving static websites

and I'm not even trying to disable useless mail addresses, because it would be pushing MIAB in a undefined behaviour zone.

> [DNS only] That's not working in this PR anyway, you said.

yup, but I intended to implement it as a second part of this PR… Once we would have discussed and considered the proper UI to implement this set of features!

I mean I'm not saying I did it right (UI wise), but the ability to disable one of the main features and not have them working always as a single block is, IMHO, a must have!

Though, obviously, if you really keep standing your ground and stay against the only idea of offering flexibility of what MIAB does, I'll find it sad but I won't fight it… I'll just end up building a way to implement my needs as post-install time patches within my own fork of the project instead of having a nice UI/UX on the project to share with everybody.

**Comment by bronson** [comment]
Sorry, I'm probably not understanding...

> the ability to disable one of the main features and not have them working always as a single block is, IMHO, a must have!

Why would any application offer the ability to disable its main feature?  That seems like an indication that it's not being used as intended, no?

**Comment by guyzmo** [comment]
I said *one of its main feature****s***. The application is *Mail* in a box, but it actually does *Mail, DNS, Web* in a box. And it's also doing calendar, remote "cloud" storage, and a bunch of other stuff.

So to be fair, *Mail In A Box* really is a glue to make things deployable and integrable more conveniently, at a time where keeping most of the tools for self hosting is harder to stay on top of. And that's what it's **main feature** is.

Then, the reality of usages is that when you're handling more than a dozen domains, a one size fit all solution won't work. 

The reality I'm living is that I got a few domains that are bound to google apps, another that uses mailgun from rackspace for the mail. But I'm still hosting them, because I'm nice and it's not taking much of my time to do it. I'm hosting mail for three domains of usergroups where the DNS is on some "neutral" zone where the admins of the group are all responsible of the zone (they are handled through the interfaces of OVH, Gandi or godaddy). And finally, because besides my own blog, I'm hosting no sites that are 100% static, I'm hosting them all in different VMs that offer different framework stacks (I usually prefer to keep PHP 💩 in a Petri dish ☺).

I generally agree with @JoshData that the tool shall have a strong use case scenario to make it simple to self host and keep control of self hosting. But it does mean as well make it *possible* to get along with border line use cases.

What I prove with that commit is that it's not hard to exclude a given domain from a given feature or another, and it does not make the code unmaintainable, we're talking here about a 200 loc change to add enough flexibility to the tool.

**Comment by JoshData** [comment]
Folks, I didn't say we wouldn't pursue these ideas at all. I only said I was closing the PR because I had particular objections. We have a bunch of open issues for discussion on these things.

The best way to move forward is to break the idea down into simpler parts that are easier for me to review one at a time. Solving #404 (the status checks are too noisy when using external DNS) first would probably help clarify what else would be useful to do.

**Pull request closed without merging**
