### PR TITLE
added Roundcube plugin vacation_sieve

### PR DESCRIPTION
**Pull request by zealot128**
I've added the vacation_sieve plugin for autoreply/out off office messages as motivated on Twitter :)

### CODE REVIEW

**Comment by jkaberg** [comment]
+1 Very nice!

**Comment by JoshData** [comment]
Fantastic. I'll merge as soon as I get a chance to try it out.

**Comment by JoshData** [comment]
Merged, thanks! I made some changes during the merge to ensure that the right version of the plugin is installed by pinning it to a commit in the remote repository, and also not reinstalling it if it is already installed on the system (by a previous run of the setup scripts).

**Comment by zealot128** [comment]
Very good! 
Thank you for creating & maintaining this great package.

**Pull request merged**
