### PR TITLE
Change Nextcloud upgrade logic to look at config.php version vs version.php version

### PR DESCRIPTION
**Pull request by jvolkenant**
Fix for #1623

PR changes so that Nextcloud download is wget_verify before deleting the install directory.  Additionally #1623 raised the issue that /usr/local/lib/owncloud/version.php was being used instead of version of user data.  So scenario's where data has been restored from an old version of MIAB on a new one, those versions would differ.

Tested as follows:
Fresh 18.04 install
Installed git master
restored data from v0.40 (running Nextcloud 13)
tested PR:
```
git remote add jvolkenant https://github.com/jvolkenant/mailinabox.git
git fetch jvolkenant
git checkout master
git merge jvolkenant/nextcloud_multi_version_upgrade
```
Verified version difference between Nextcloud installed from git master and Nextcloud user database restored from backup

```


root@m:~/mailinabox# STORAGE_ROOT=/home/user-data php -r "include(\"$STORAGE_ROOT/owncloud/config.php\"); echo(\$CONFIG['version']);"
13.0.6.1
root@m:~/mailinabox# grep OC_Version /usr/local/lib/owncloud/version.php 
$OC_Version = array(15,0,8,1);
$OC_VersionString = '15.0.8';
$OC_VersionCanBeUpgradedFrom = array (
```
ran setup/start.sh which is git head with PR
```

Primary Hostname: snip
Public IP Address: snip
Mail-in-a-Box Version:  v0.42b-6-g6bbdd75

Updating system packages...
Installing system packages...
Initializing system random number generator...
Firewall is active and enabled on system startup
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Installing Nextcloud (contacts/calendar)...
Upgrading Nextcloud --- backing up existing installation, configuration, and database to directory to /home/user-data/owncloud-backup/2019-08-23-13:48:39...

Upgrading to Nextcloud version 14.0.6

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Disabled incompatible app: contacts
Updating <calendar> ...
Updated <calendar> to 1.6.5
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.4.0
Updating <files_texteditor> ...
Updated <files_texteditor> to 2.6.0
Updating <files_videoplayer> ...
Updated <files_videoplayer> to 1.3.0
Updating <gallery> ...
Updated <gallery> to 18.1.0
Updating <password_policy> ...
Updated <password_policy> to 1.4.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.4.0
Updating <serverinfo> ...
Updated <serverinfo> to 1.4.0
Updating <survey_client> ...
Updated <survey_client> to 1.2.0
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.3.1
Updating <updatenotification> ...
Updated <updatenotification> to 1.4.1
Updating <federation> ...
Updated <federation> to 1.4.0
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.2.0
Updating <oauth2> ...
Updated <oauth2> to 1.2.1
Updating <files> ...
Updated <files> to 1.9.0
Updating <activity> ...
Updated <activity> to 2.7.0
Updating <dav> ...
Fix broken values of calendar objects

 Done
    0/0 [>---------------------------]   0%
Updated <dav> to 1.6.1
Updating <files_sharing> ...
Updated <files_sharing> to 1.6.2
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.4.1
Updating <files_versions> ...
Updated <files_versions> to 1.7.1
Updating <sharebymail> ...
Updated <sharebymail> to 1.4.0
Updating <workflowengine> ...
Updated <workflowengine> to 1.4.0
Updating <comments> ...
Updated <comments> to 1.4.0
Updating <nextcloud_announcements> ...
Updated <nextcloud_announcements> to 1.3.0
Updating <notifications> ...
Updated <notifications> to 2.2.1
Updating <systemtags> ...
Updated <systemtags> to 1.4.0
Updating <theming> ...
Updated <theming> to 1.5.0
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore 
Checking for update of app calendar in appstore
Checked for update of app "calendar" in appstore 
Checking for update of app cloud_federation_api in appstore
Checked for update of app "cloud_federation_api" in appstore 
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore 
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore 
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore 
Checking for update of app federation in appstore
Checked for update of app "federation" in appstore 
Checking for update of app files in appstore
Checked for update of app "files" in appstore 
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in appstore 
Checking for update of app files_texteditor in appstore
Checked for update of app "files_texteditor" in appstore 
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in appstore 
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in appstore 
Checking for update of app files_videoplayer in appstore
Checked for update of app "files_videoplayer" in appstore 
Checking for update of app gallery in appstore
Checked for update of app "gallery" in appstore 
Checking for update of app logreader in appstore
Checked for update of app "logreader" in appstore 
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in appstore 
Checking for update of app nextcloud_announcements in appstore
Checked for update of app "nextcloud_announcements" in appstore 
Checking for update of app notifications in appstore
Checked for update of app "notifications" in appstore 
Checking for update of app oauth2 in appstore
Checked for update of app "oauth2" in appstore 
Checking for update of app password_policy in appstore
Checked for update of app "password_policy" in appstore 
Checking for update of app provisioning_api in appstore
Checked for update of app "provisioning_api" in appstore 
Checking for update of app serverinfo in appstore
Checked for update of app "serverinfo" in appstore 
Checking for update of app sharebymail in appstore
Checked for update of app "sharebymail" in appstore 
Checking for update of app survey_client in appstore
Checked for update of app "survey_client" in appstore 
Checking for update of app systemtags in appstore
Checked for update of app "systemtags" in appstore 
Checking for update of app theming in appstore
Checked for update of app "theming" in appstore 
Checking for update of app twofactor_backupcodes in appstore
Checked for update of app "twofactor_backupcodes" in appstore 
Checking for update of app updatenotification in appstore
Checked for update of app "updatenotification" in appstore 
Checking for update of app user_external in appstore
Checked for update of app "user_external" in appstore 
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in appstore 
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Reset log level
Check indices of the share table.
Adding additional mtime index to the filecache table, this can take some time...
Filecache table updated successfully.
This can take up to hours, depending on the number of files in your instance!

Upgrading to Nextcloud version 15.0.8

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <accessibility> ...
Updated <accessibility> to 1.1.0
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.5.0
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 1.4.0
Updating <files_texteditor> ...
Updated <files_texteditor> to 2.7.0
Updating <files_videoplayer> ...
Updated <files_videoplayer> to 1.4.0
Updating <gallery> ...
Updated <gallery> to 18.2.0
Updating <password_policy> ...
Updated <password_policy> to 1.5.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.5.0
Updating <serverinfo> ...
Updated <serverinfo> to 1.5.0
Updating <survey_client> ...
Updated <survey_client> to 1.3.0
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.4.1
Updating <updatenotification> ...
Updated <updatenotification> to 1.5.0
Updating <federation> ...
Updated <federation> to 1.5.0
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.3.0
Updating <oauth2> ...
Updated <oauth2> to 1.3.0
Updating <user_external> ...
Updated <user_external> to 0.6.3
Updating <files> ...
Updated <files> to 1.10.0
Updating <activity> ...
Updated <activity> to 2.8.2
Updating <cloud_federation_api> ...
Updated <cloud_federation_api> to 0.1.0
Updating <dav> ...
Fix broken values of calendar objects

 Done
    0/0 [>---------------------------]   0%
Updated <dav> to 1.8.2
Updating <files_sharing> ...
Updated <files_sharing> to 1.7.0
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.5.0
Updating <files_versions> ...
Updated <files_versions> to 1.8.0
Updating <sharebymail> ...
Updated <sharebymail> to 1.5.0
Updating <workflowengine> ...
Updated <workflowengine> to 1.5.0
Updating <comments> ...
Updated <comments> to 1.5.0
Updating <nextcloud_announcements> ...
Updated <nextcloud_announcements> to 1.4.0
Updating <notifications> ...
Updated <notifications> to 2.3.0
Updating <systemtags> ...
Updated <systemtags> to 1.5.0
Updating <theming> ...
Updated <theming> to 1.6.0
Checking for update of app accessibility in appstore
Checked for update of app "accessibility" in appstore 
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore 
Checking for update of app calendar in appstore
Checked for update of app "calendar" in appstore 
Checking for update of app cloud_federation_api in appstore
Checked for update of app "cloud_federation_api" in appstore 
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore 
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore 
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore 
Checking for update of app federation in appstore
Checked for update of app "federation" in appstore 
Checking for update of app files in appstore
Checked for update of app "files" in appstore 
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in appstore 
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in appstore 
Checking for update of app files_texteditor in appstore
Checked for update of app "files_texteditor" in appstore 
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in appstore 
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in appstore 
Checking for update of app files_videoplayer in appstore
Checked for update of app "files_videoplayer" in appstore 
Checking for update of app gallery in appstore
Checked for update of app "gallery" in appstore 
Checking for update of app logreader in appstore
Checked for update of app "logreader" in appstore 
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in appstore 
Checking for update of app nextcloud_announcements in appstore
Checked for update of app "nextcloud_announcements" in appstore 
Checking for update of app notifications in appstore
Checked for update of app "notifications" in appstore 
Checking for update of app oauth2 in appstore
Checked for update of app "oauth2" in appstore 
Checking for update of app password_policy in appstore
Checked for update of app "password_policy" in appstore 
Checking for update of app provisioning_api in appstore
Checked for update of app "provisioning_api" in appstore 
Checking for update of app serverinfo in appstore
Checked for update of app "serverinfo" in appstore 
Checking for update of app sharebymail in appstore
Checked for update of app "sharebymail" in appstore 
Checking for update of app support in appstore
Checked for update of app "support" in appstore 
Checking for update of app survey_client in appstore
Checked for update of app "survey_client" in appstore 
Checking for update of app systemtags in appstore
Checked for update of app "systemtags" in appstore 
Checking for update of app theming in appstore
Checked for update of app "theming" in appstore 
Checking for update of app twofactor_backupcodes in appstore
Checked for update of app "twofactor_backupcodes" in appstore 
Checking for update of app updatenotification in appstore
Checked for update of app "updatenotification" in appstore 
Checking for update of app user_external in appstore
Update app user_external from appstore
Checked for update of app "user_external" in appstore 
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in appstore 
Remove potentially over exposing share links
 Done
    0/0 [>---------------------------]   0%
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Reset log level
Check indices of the share table.
Adding additional owner index to the share table, this can take some time...
Share table updated successfully.
Adding additional initiator index to the share table, this can take some time...
Share table updated successfully.
All tables already up to date!
Nextcloud is already latest version
Installing Z-Push (Exchange/ActiveSync server)...
Installing Mail-in-a-Box system management daemon...
Installing Munin (system monitoring)...
updated DNS: snip
web updated

-----------------------------------------------

Your Mail-in-a-Box is running.

Please log in to the control panel for further instructions at:

https://snip/admin

You will be alerted that the website has an invalid certificate. Check that
the certificate fingerprint matches:

9C...snip

Then you can confirm the security exception and continue.
```

### CODE REVIEW

**Comment by jvolkenant** [comment]
I still need to test a fresh install with this patch, I don't think it will be a problem, but I just haven't done it yet.

**Comment by anoma** [comment]
You may want to ignore this as I was starting with a broken Nextcloud system caused by PEBCAK trying to fix the failed v0.30 to v0.42b restore before this PR started but all goes well at first and then maintenance mode causes a problem.

I will hold off on running it again or making any other changes in case you would like something specific changed and tested. Let me know.

```
Installing Nextcloud (contacts/calendar)...
Upgrading Nextcloud --- backing up existing installation, configuration, and database to directory to /home/user-data/owncloud-backup/2019-08-26-08:11:12...

Upgrading to Nextcloud version 14.0.6

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Disabled incompatible app: bruteforcesettings
Disabled incompatible app: contacts
Disabled incompatible app: templateeditor
Updating <calendar> ...
Updated <calendar> to 1.6.5
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.4.0
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 1.3.2
Updating <files_texteditor> ...
Updated <files_texteditor> to 2.6.0
Updating <files_videoplayer> ...
Updated <files_videoplayer> to 1.3.0
Updating <gallery> ...
Updated <gallery> to 18.1.0
Updating <password_policy> ...
Updated <password_policy> to 1.4.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.4.0
Updating <serverinfo> ...
Updated <serverinfo> to 1.4.0
Updating <survey_client> ...
Updated <survey_client> to 1.2.0
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.3.1
Updating <updatenotification> ...
Updated <updatenotification> to 1.4.1
Updating <federation> ...
Updated <federation> to 1.4.0
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.2.0
Updating <oauth2> ...
Updated <oauth2> to 1.2.1
Updating <files> ...
Updated <files> to 1.9.0
Updating <activity> ...
Updated <activity> to 2.7.0
Updating <dav> ...
Fix broken values of calendar objects

 Done
    0/0 [>---------------------------]   0%
Updated <dav> to 1.6.1
Updating <files_sharing> ...
Updated <files_sharing> to 1.6.2
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.4.1
Updating <files_versions> ...
Updated <files_versions> to 1.7.1
Updating <sharebymail> ...
Updated <sharebymail> to 1.4.0
Updating <workflowengine> ...
Updated <workflowengine> to 1.4.0
Updating <comments> ...
Updated <comments> to 1.4.0
Updating <nextcloud_announcements> ...
Updated <nextcloud_announcements> to 1.3.0
Updating <notifications> ...
Updated <notifications> to 2.2.1
Updating <systemtags> ...
Updated <systemtags> to 1.4.0
Updating <theming> ...
Updated <theming> to 1.5.0
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore
Checking for update of app calendar in appstore
Checked for update of app "calendar" in appstore
Checking for update of app cloud_federation_api in appstore
Checked for update of app "cloud_federation_api" in appstore
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore
Checking for update of app federation in appstore
Checked for update of app "federation" in appstore
Checking for update of app files in appstore
Checked for update of app "files" in appstore
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in appstore
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in appstore
Checking for update of app files_texteditor in appstore
Checked for update of app "files_texteditor" in appstore
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in appstore
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in appstore
Checking for update of app files_videoplayer in appstore
Checked for update of app "files_videoplayer" in appstore
Checking for update of app gallery in appstore
Checked for update of app "gallery" in appstore
Checking for update of app logreader in appstore
Checked for update of app "logreader" in appstore
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in appstore
Checking for update of app nextcloud_announcements in appstore
Checked for update of app "nextcloud_announcements" in appstore
Checking for update of app notifications in appstore
Checked for update of app "notifications" in appstore
Checking for update of app oauth2 in appstore
Checked for update of app "oauth2" in appstore
Checking for update of app password_policy in appstore
Checked for update of app "password_policy" in appstore
Checking for update of app provisioning_api in appstore
Checked for update of app "provisioning_api" in appstore
Checking for update of app serverinfo in appstore
Checked for update of app "serverinfo" in appstore
Checking for update of app sharebymail in appstore
Checked for update of app "sharebymail" in appstore
Checking for update of app survey_client in appstore
Checked for update of app "survey_client" in appstore
Checking for update of app systemtags in appstore
Checked for update of app "systemtags" in appstore
Checking for update of app theming in appstore
Checked for update of app "theming" in appstore
Checking for update of app twofactor_backupcodes in appstore
Checked for update of app "twofactor_backupcodes" in appstore
Checking for update of app updatenotification in appstore
Checked for update of app "updatenotification" in appstore
Checking for update of app user_external in appstore
Checked for update of app "user_external" in appstore
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in appstore
Starting code integrity check...
Finished code integrity check
Update successful
Maintenance mode is kept active
Reset log level
Nextcloud is in maintenance mode - no apps have been loaded

Check indices of the share table.
Adding additional share_with index to the share table, this can take some time...
Share table updated successfully.
Adding additional parent index to the share table, this can take some time...
Share table updated successfully.
Adding additional mtime index to the filecache table, this can take some time...
Filecache table updated successfully.
Nextcloud is in maintenance mode - no apps have been loaded

This can take up to hours, depending on the number of files in your instance!

Upgrading to Nextcloud version 15.0.8

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Updating <accessibility> ...
Updated <accessibility> to 1.1.0
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.5.0
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 1.4.0
Updating <files_texteditor> ...
Updated <files_texteditor> to 2.7.0
Updating <files_videoplayer> ...
Updated <files_videoplayer> to 1.4.0
Updating <gallery> ...
Updated <gallery> to 18.2.0
Updating <password_policy> ...
Updated <password_policy> to 1.5.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.5.0
Updating <serverinfo> ...
Updated <serverinfo> to 1.5.0
Updating <survey_client> ...
Updated <survey_client> to 1.3.0
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.4.1
Updating <updatenotification> ...
Updated <updatenotification> to 1.5.0
Updating <federation> ...
Updated <federation> to 1.5.0
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.3.0
Updating <oauth2> ...
Updated <oauth2> to 1.3.0
Updating <user_external> ...
Updated <user_external> to 0.6.3
Updating <files> ...
Updated <files> to 1.10.0
Updating <activity> ...
Updated <activity> to 2.8.2
Updating <cloud_federation_api> ...
Updated <cloud_federation_api> to 0.1.0
Updating <dav> ...
Fix broken values of calendar objects

 Done
    0/0 [>---------------------------]   0%
Updated <dav> to 1.8.2
Updating <files_sharing> ...
Updated <files_sharing> to 1.7.0
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.5.0
Updating <files_versions> ...
Updated <files_versions> to 1.8.0
Updating <sharebymail> ...
Updated <sharebymail> to 1.5.0
Updating <workflowengine> ...
Updated <workflowengine> to 1.5.0
Updating <comments> ...
Updated <comments> to 1.5.0
Updating <nextcloud_announcements> ...
Updated <nextcloud_announcements> to 1.4.0
Updating <notifications> ...
Updated <notifications> to 2.3.0
Updating <systemtags> ...
Updated <systemtags> to 1.5.0
Updating <theming> ...
Updated <theming> to 1.6.0
Checking for update of app accessibility in appstore
Checked for update of app "accessibility" in appstore
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore
Checking for update of app calendar in appstore
Checked for update of app "calendar" in appstore
Checking for update of app cloud_federation_api in appstore
Checked for update of app "cloud_federation_api" in appstore
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore
Checking for update of app federation in appstore
Checked for update of app "federation" in appstore
Checking for update of app files in appstore
Checked for update of app "files" in appstore
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in appstore
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in appstore
Checking for update of app files_texteditor in appstore
Checked for update of app "files_texteditor" in appstore
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in appstore
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in appstore
Checking for update of app files_videoplayer in appstore
Checked for update of app "files_videoplayer" in appstore
Checking for update of app gallery in appstore
Checked for update of app "gallery" in appstore
Checking for update of app logreader in appstore
Checked for update of app "logreader" in appstore
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in appstore
Checking for update of app nextcloud_announcements in appstore
Checked for update of app "nextcloud_announcements" in appstore
Checking for update of app notifications in appstore
Checked for update of app "notifications" in appstore
Checking for update of app oauth2 in appstore
Checked for update of app "oauth2" in appstore
Checking for update of app password_policy in appstore
Checked for update of app "password_policy" in appstore
Checking for update of app provisioning_api in appstore
Checked for update of app "provisioning_api" in appstore
Checking for update of app serverinfo in appstore
Checked for update of app "serverinfo" in appstore
Checking for update of app sharebymail in appstore
Checked for update of app "sharebymail" in appstore
Checking for update of app support in appstore
Checked for update of app "support" in appstore
Checking for update of app survey_client in appstore
Checked for update of app "survey_client" in appstore
Checking for update of app systemtags in appstore
Checked for update of app "systemtags" in appstore
Checking for update of app theming in appstore
Checked for update of app "theming" in appstore
Checking for update of app twofactor_backupcodes in appstore
Checked for update of app "twofactor_backupcodes" in appstore
Checking for update of app updatenotification in appstore
Checked for update of app "updatenotification" in appstore
Checking for update of app user_external in appstore
Update app user_external from appstore
Checked for update of app "user_external" in appstore
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in appstore
Remove potentially over exposing share links
 Done
    0/0 [>---------------------------]   0%
Starting code integrity check...
Finished code integrity check
Update successful
Maintenance mode is kept active
Reset log level
Nextcloud is in maintenance mode - no apps have been loaded

Check indices of the share table.
Adding additional owner index to the share table, this can take some time...
Share table updated successfully.
Adding additional initiator index to the share table, this can take some time...
Share table updated successfully.
Nextcloud is in maintenance mode - no apps have been loaded

All tables already up to date!
Nextcloud is in maintenance mode - no apps have been loaded

<warning>Nextcloud is in maintenance mode</warning>
Maybe an upgrade is already in process. Please check the logfile (data/nextcloud.log). If you want to re-run the upgrade procedure, remove the "maintenance mode" from config.php and call this script again.
```

**Comment by anoma** [comment]
OK so I got this working. Following on directly from the maintenace mode error above I ran the installer again.

This time:

```
Installing Nextcloud (contacts/calendar)...
Nextcloud is in maintenance mode - no apps have been loaded

<warning>Nextcloud is in maintenance mode</warning>
Maybe an upgrade is already in process. Please check the logfile (data/nextcloud.log). If you want to re-run the upgrade procedure, remove the "maintenance mode" from config.php and call this script again.
```

Now this is fine as the feedback makes sense but the whole mailinabox installer bombs out. This should not happen. NextCloud should not stop the entire mailinabox installer mid install/upgrade just because it is in maintenance mode.  (This is the very first problem symptom I seen that started this whole saga of problems and I dont believe it limited to this PR.)

The good news is using this PR you can recover by simply:

`sudo -u www-data php /usr/local/lib/owncloud/occ maintenance:mode --off`

and running the mailinabox installer again it will complete showing

```
Installing Nextcloud (contacts/calendar)...
Nextcloud is already latest version
```

and NextCloud also works.

**Comment by JoshData** [comment]
Thanks all!

**Pull request merged**
