### PR TITLE
#1161 Move the config line for mail_domain to always reset the PRIMARY_HOST

### PR DESCRIPTION
**Pull request by macmedia**
Cant we just move the line when the $PRIMARY_HOST is set down a few lines? That way its set regardless of the file already being present.

### CODE REVIEW

**Comment by JoshData** [comment]
Yup.

Did you test it?

**Comment by macmedia** [comment]
I tested on a virtual box to make sure the config.php file was being updated. Each change of the hostname does update the file correctly.

**Comment by JoshData** [comment]
Great thanks! If you could add a changelog entry that'd be great. 

On April 24, 2017 6:46:58 PM EDT, Git Repository <notifications@github.com> wrote:
>I tested on a virtual box to make sure the config.php file was being
>updated. Each change of the hostname does update the file correctly.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/mail-in-a-box/mailinabox/pull/1163#issuecomment-296843253

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JoshData** [comment]
Almost. Your changelog entry should go in the In Development section at the top next to the other ownCloud-related entry above it (not in a new `v0.22a (April 24, 2017)` section that you created).

**Comment by JoshData** [comment]
Thanks!

**Comment by macmedia** [comment]
Somehow I change the file that you merged. Sorry, new to GIT. The file has an error. How do I go about fixing this, should I submit a new PR? Sorry again for the extra headache.

```
-\$CONFIG['mail_domain'] => '$PRIMARY_HOSTNAME',
+\$CONFIG['mail_domain'] = '$PRIMARY_HOSTNAME';
```

**Comment by yodax** [comment]
I see this was in the first commit already, see [here](https://github.com/mail-in-a-box/mailinabox/pull/1163/commits/4f5c749e057a6dc894e727550b1f5e0db7ae6c6f). I created a [PR](https://github.com/mail-in-a-box/mailinabox/issues/1172) to fix this and retested the PR on both a new box and an upgrade.

**Comment by macmedia** [comment]
Thank you

**Comment by yodax** [comment]
You're welcome!

**Pull request merged**
