### PR TITLE
sieve-spam.txt do not stop evaluation

### PR DESCRIPTION
**Pull request by h8h**
Hi 

I want to be able to discard messages with "X-Spam-Status" = ^YES

To do that I create a sieve in roundcube mail. 

But since the evaluation of Spam e-mails is stopped at a very early step of the processing the roundcube dovecot filter does not apply.

To make that possible the `stop;`command is removed.

### CODE REVIEW

**Comment by h8h** [comment]
I figure out that it was not the `stop;` - command.

It is the order.

E-Mail is not SPAM (X-Spam-Status != ^YES)
```
      ## Started executing script 'sieve-spam'
   3: jump if result is false
   3:   jumping to line 4
      ## Finished executing script 'sieve-spam'


      ## Started executing script 'roundcube'
   3: jump if result is false
   3:   jumping to line 10
      ## Finished executing script 'roundcube'
```

E-Mail is not SPAM (X-Spam-Status != ^YES)
```

      ## Started executing script 'sieve-spam'
   3: jump if result is false
   3:   not jumping
   4: fileinto action
   4:   store message in mailbox `Spam'
      ## Finished executing script 'sieve-spam'
```

As you can see, the roundcube sieve does not get evaluated.


After changing the order:
```
/etc/dovecot/conf.d/99-local-sieve.conf
plugin {
  sieve_before = /home/user-data/mail/sieve/global_before
  sieve_after = /home/user-data/mail/sieve/global_after
  sieve_after2 = /etc/dovecot/sieve-spam.sieve
  sieve = /home/user-data/mail/sieve/%d/%n.sieve
  sieve_dir = /home/user-data/mail/sieve/%d/%n
}
``` 

E-Mail is not SPAM (X-Spam-Status != ^YES)
``` 
      ## Started executing script 'roundcube'
   3: jump if result is false
   3:   jumping to line 5
      ## Finished executing script 'roundcube'


      ## Started executing script 'sieve-spam'
   3: jump if result is false
   3:   jumping to line 4
      ## Finished executing script 'sieve-spam'
```



E-Mail is SPAM (X-Spam-Status == ^YES)
``` 
      ## Started executing script 'roundcube'
   3: jump if result is false
   3:   not jumping
   5: reject action
   5:   reject message with reason `Diese Mail ist SPAM. ??This E-Mail is SPAM.??'
      ## Finished executing script 'roundcube
```


So for that particular use case it works. 

Any thoughts on this?

If that is okay to change the order than I will update my PR.

**Comment by Bretto699** [comment]
@

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jvolkenant** [comment]
I have this in order to move mails that are spam to the inbox via a roundcube rule (So I can have the mail scraped by another email provider). Both edits were nessessary.

```
root@m:~# cat 99-local-sieve.conf
plugin {
 sieve_before = /home/user-data/mail/sieve/global_before
 sieve_after = /etc/dovecot/sieve-spam.sieve
 sieve_after2 = /home/user-data/mail/sieve/global_after
 sieve = /home/user-data/mail/sieve/%d/%n.sieve
 sieve_dir = /home/user-data/mail/sieve/%d/%n
}
root@m:~# cat sieve-spam.sieve
require ["regex", "fileinto", "imap4flags"];

if allof (header :regex "X-Spam-Status" "^Yes") {
  fileinto "Spam";
}
```

**Comment by h8h** [comment]
It is very confusing for me why dovecot sieve stop the evaluation, even without the `stop;` command.

I expected the following (regardless the order)

```

      ## Started executing script 'sieve-spam'
   3: jump if result is false
   3:   not jumping
   4: fileinto action
   4:   store message in mailbox `Spam'
      ## Finished executing script 'sieve-spam'


      ## Started executing script 'roundcube'
   3: jump if result is false
   3:   not jumping
   5: reject action
   5:   reject message with reason `Diese Mail ist SPAM. ??This E-Mail is SPAM.??'
      ## Finished executing script 'roundcube
```

**Comment by h8h** [comment]
I close this. 

Because this has impact on the vacation filter.

Because if rule processing do not stop, the SPAM E-Mail gets also the vacation autoreply.

For my particular case I changed the `/etc/dovecot/sieve-spam.sieve` manually and did an ` sievec /etc/dovecot/sieve-spam.sieve` and an `chown mail.dovecot /etc/dovecot/sieve-spam.svbin` afterwards.

**Pull request closed without merging**
