### PR TITLE
Backup Amazon S3: Added support for custom endpoints

### PR DESCRIPTION
**Pull request by JumpLink**
There are some Amazon S3 compatible storage in the wild. This pull request makes it possible to set a custom endpoint to support such storage (In my case tested with DigitalOcean spaces).

### CODE REVIEW

**Comment by JoshData** [comment]
Nice work!

I'll review further likely after the Ubuntu 18.04 changes are merged, which should be in a few weeks.

**Comment by axilleas** [comment]
Hi! I just tested this locally and it worked great with DigitalOcean spaces!

The only thing I found strange, is that the endpoint is not persisted in the backup form. So, after I saved the values, it shows like this (not sure this is how the default Amazon S3 works):

screenshot_2018-10-06 mailinabox lan - mail-in-a-box control panel

**Comment by axilleas** [comment]
I've been using this in production for 23 days now with DigitalOcean Spaces, seems to work fine.

**Comment by JoshData** [comment]
No, it'll have to wait until after the branch is released, sorry.

**Comment by avenirf** [comment]
Do you know when this patch will be released? As I migrated to new v0.41 and found out about backup to AWS S3 problem.

**Comment by JoshData** [comment]
If someone tests it with the latest Mail-in-a-Box, I'll merge it. Thanks.

**Comment by just4t** [comment]
@Joshdata I'm currently using it over v.0.41 to backup to my DigitalOcean Spaces (S3 compat.) as post-install patch by replacing the default `/root/mailinabox/management/backup.py` and `/root/mailinabox/management/templates/system-backup.py` files by the patched ones and WORKS, by following this steps:

Here the ['patched' files](https://1drv.ms/u/s!AuZEMrA0wRV7hAb6u6kCIWjQ2d2_)

- Install Mail-in-a-Box v.041
- Turn-off backups at admin panel.
- Replace the mnetioned files by the ones that include the patch
- Reboot the server
- Config. your S3 compatible account at admin panel
- Order a full backup through SSH

**[IMPORTANT]** I tryied to apply the mentioned patch directly into my Mail-in-a-Box **fork** in advance and tryed to setup the Mial-in-a-Box installation from there but seems doing it that way the backups admin panel hangs and can't be stopped/ configured ... I'm still trying to debug it, I will try it again tonight and I'll report if success.

**Comment by jvolkenant** [comment]
Curious if anyone has tested this with https://github.com/minio/minio,  I tried a little while ago, but couldn't get things working (give I've not used s3 much).  Some research makes me think boto doesn't work with minio anyway.

**Comment by just4t** [comment]
@JoshData Were retested and already confirmed that the patch works and @JumpLink already provided an acceptable pull request, again ... **What do you need more from us to accept to merge it?**

**Comment by JoshData** [comment]
Thanks for the ping. Merged!

**Comment by nikhilbhardwaj** [comment]
I have v043 and still don't see this feature. Can someone share what version I need to work with Minio.

**Comment by fm** [comment]
@nikhilbhardwaj you need to select “Backup to S3”, then in region select “Other” and in endpoint out the S3 compatible endpoint of your service and fill out the other details as needed with the info given by your S3 compatible provider

**Comment by nikhilbhardwaj** [comment]
@fm thanks for your response, unfortunately that doesn't work.

What happens is that the popup displays this heading `Backup configuration
` and message - `Enter an S3 bucket name.` regardless of this information being present or not.

Here's a screenshot -
Screen Shot 2020-01-27 at 11 08 34 AM

**Comment by fm** [comment]
Ah.. I see what is happening, the endpoint should be the URL without https://

**Comment by nikhilbhardwaj** [comment]
Thanks, that definitely helped moving things forward, now it does try to connect to the server but the server returns a 504.

```html
<html>
 <head><title>504 Gateway Time-out</title></head>
 <body bgcolor="white"> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body>
 </html>
 <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->
```

I was taking a look at the [minio docs](https://docs.min.io/docs/how-to-use-aws-sdk-for-python-with-minio-server.html) and suspect that the `signature_version='s3v4'` may not be set as this was never specified from the UI.

Any thoughts or ideas on this?

**Comment by fm** [comment]
I'm not sure, never used Minio. I used [Exoscale's S3 API](https://community.exoscale.com/api/sos/) and it worked without errors after specifying the endpoint, path and keys.

**Comment by itnok** [comment]
Was anybody able to use MinIO as backup?
If yes, how? _(Tried almost everything I could think about in the form fields, but nothing seems to work)_

**Comment by jvolkenant** [comment]
I wasn't able to get minio working a while back.  I don't think it supports the same version of API that boto needs or something.

**Comment by durd** [comment]
I don't think it's minios fault. I can't get MIAB to even try to talk to my minio(via caddy proxy). I'm checking logs, and tcpdumping my minios host-ip.

**Comment by durd** [comment]
@jvolkenant, @itnok 
MIAB is using an "old" version of boto (v2.49.0), there is a [version 3](https://github.com/boto/boto3) that is stable and recommended. However, that requires a rewrite of MIABs boto integration as syntax is different. I'm not sure how different so it could be easy or hard. A big change is that the protocol needs to be written out (https:// in my case below)

Below is against the latest minio hosted at my home through Caddy https reverse proxy.

boto v2.49.0 (python3)
```
>>> import boto.s3
>>> from boto.exception import BotoServerError
>>> from boto.s3.connection import S3Connection
>>> region = boto.s3.S3RegionInfo(name='mail', endpoint='whodis.net', connection_cls=S3Connection)
>>> conn = region.connect(aws_access_key_id='what', aws_secret_access_key='naw')
>>> print(conn.get_bucket('mail'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/david/.virtualenvs/boto3/venv/lib/python3.8/site-packages/boto/s3/connection.py", line 509, in get_bucket
    return self.head_bucket(bucket_name, headers=headers)
  File "/Users/david/.virtualenvs/boto3/venv/lib/python3.8/site-packages/boto/s3/connection.py", line 528, in head_bucket
    response = self.make_request('HEAD', bucket_name, headers=headers)
  File "/Users/david/.virtualenvs/boto3/venv/lib/python3.8/site-packages/boto/s3/connection.py", line 667, in make_request
    return super(S3Connection, self).make_request(
  File "/Users/david/.virtualenvs/boto3/venv/lib/python3.8/site-packages/boto/connection.py", line 1070, in make_request
    return self._mexe(http_request, sender, override_num_retries,
  File "/Users/david/.virtualenvs/boto3/venv/lib/python3.8/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
  File "/Users/david/.virtualenvs/boto3/venv/lib/python3.8/site-packages/boto/connection.py", line 942, in _mexe
    connection.request(request.method, request.path,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

boto3 (python3)
```
>>> import boto3
>>> import boto3.session
>>>
>>> sess = boto3.session.Session(aws_access_key_id='again', aws_secret_access_key='stop')
>>>
>>> s3 = sess.client('s3', endpoint_url='https://norlly.net')
>>> #s3 = sess.resource('s3')
>>> response = s3.list_buckets()
>>> print('Existing buckets:')
Existing buckets:
>>> for bucket in response['Buckets']:
...     print(f'  {bucket["Name"]}')
...
  mail
```

I'll try to create a separate issue for this later on today.

**Pull request merged**
