### PR TITLE
Update Roundcube to 1.1.5

### PR DESCRIPTION
**Pull request by aspdye**
- Update to Roundcube 1.1.5 and use the new SHA256 Hash 😉
- Fetch Roundcube from GitHub (https://github.com/roundcube/roundcubemail/releases)

### CODE REVIEW

**Comment by yodax** [comment]
Was about to reply about start.sh, but you caught it :+1:

**Comment by aspdye** [comment]
Stupid question @yodax but do you know, which hashes we use (md5, sha-1, ...) 😁

**Comment by yodax** [comment]
In functions.sh wget_verify uses sha1sum.

**Comment by aspdye** [comment]
fixed 😉

**Comment by yodax** [comment]
Looks like an important security release.

**Comment by aspdye** [comment]
@yodax what do you think about using GitHub instead of the AWS mirror 😁 We have created this mirror because of SourceForge - and i think GitHub is stable 😉

**Comment by yodax** [comment]
If github isn't working, the bootstrapper will also not work so it should be safe. Moving to github will probably save @joshdata a few bucks too. So imho github should be fine.

**Comment by JoshData** [comment]
Please don't submit PRs that do logically unrelated things. If you un-rename the file, I'll merge. Also "Mirror" should be lowercase.

**Comment by aspdye** [comment]
Done :wink:

**Comment by JoshData** [comment]
Thanks!

**Pull request merged**
