### PR TITLE
Focus on fields in the login form

### PR DESCRIPTION
**Pull request by badsyntax**
This just makes life a little easier.

### CODE REVIEW

**Comment by JoshData** [comment]
Could you just test for the existence of `.trim` before using it? It's [IE9+](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim) and in principle the site is otherwise usable with IE8... probably.

**Comment by badsyntax** [comment]
Ahh I see, I wasn't sure of the supported browsers. I'll make that change...

**Comment by badsyntax** [comment]
Ok i've rebased with that change.

**Comment by JoshData** [comment]
Thanks!

**Pull request merged**
