### PR TITLE
roundcube:  upgrade carddav plugin to 3.0.3 & updated migrate.py

### PR DESCRIPTION
**Pull request by jvolkenant**
Similar to #1458, but adds migration script to dump db contents at upgrade

### CODE REVIEW

**Comment by JoshData** [comment]
Nice. I'll try it out when I get the chance.

**Comment by jvolkenant** [comment]
I'll work on those and update the PR

**Comment by jvolkenant** [comment]
Added those recommendations.

**Comment by JoshData** [comment]
Thanks!

**Pull request merged**
