### PR TITLE
Add missing form method to keep LastPass happy

### PR DESCRIPTION
**Pull request by binarykitchen**
Also removes some trailing whitespaces.

Idea comes from https://github.com/mail-in-a-box/mailinabox/issues/1549

### CODE REVIEW

**Comment by JoshData** [comment]
Do we need the methods on the form other than the login one?

**Comment by binarykitchen** [comment]
Not really, just being consistent here. Can remove in others if you prefer.

**Comment by JoshData** [comment]
Yep, please remove. Let's only change what needs fixing.

**Comment by binarykitchen** [comment]
@JoshData ok, here you go

**Comment by JoshData** [comment]
Thanks!

**Pull request merged**
