### PR TITLE
Allow dns zone transfer from IPv6

### PR DESCRIPTION
**Pull request by notEvil**
A small step towards IPv6

### CODE REVIEW

**Comment by JoshData** [comment]
A domain can resolve to both an IPv4 and an IPv6 address, and in that case we would end up returning both. Will that work? If so, domains can also resolve to multiple IPv4 and/or multiple IPv6 addresses, and maybe we should return the whole set rather then the first of each.

**Comment by notEvil** [comment]
I don't know if I follow. Do you suggest to change `values.append(str(ipv6_response[0]))` into `values.extend(map(str, ipv6_response))` and similar for ipv4? The change here already does what you are describing (returns both).

**Comment by JoshData** [comment]
Right. If ipv6_response or ipv4_response each contain more than one value, we might as well return all of them, rather than just the first IPv6 address and the first IPv4 address.

**Comment by JoshData** [comment]
Thanks, that makes the code a bit cleaner.

**Pull request merged**
