### PR TITLE
Include html5_notifier by default

### PR DESCRIPTION
**Pull request by Hoekynl**
Includes the roundcube plugin html_notifier by default.

It "git clone" the latest version of html5_notifier to "/usr/local/lib/roundcubemail/plugins/html5_notifier"
It adds "html5_notifier" to $config['plugins']

### CODE REVIEW

**Comment by JoshData** [comment]
Try to run the install with your changes and see what happens.

**Comment by Hoekynl** [comment]
No errors returned, and html5_notifier is installed successfully.

**Comment by JoshData** [comment]
Not because of your changes though.

**Comment by Hoekynl** [comment]
Let me see, ill run it again

**Comment by Hoekynl** [comment]
I edited the script, its working now (latest version).
Only thing missing is :$HTML5_NOTIFIER_VERSION in the UPDATE_KEY.
As soon as I add that, it breaks and doesn't work anymore.

**Comment by JoshData** [comment]
What do you mean it breaks? What happens?

**Comment by Hoekynl** [comment]
It doesn't git clone the html5_notifier anymore, I cant see why. Is there a way to see errors it creates? I can only see "installing roundcube" now.

**Comment by JoshData** [comment]
You could modify the git_clone function in `functions.sh` to output more, I guess.

**Comment by Hoekynl** [comment]
Isn't there a simple explanation why it wont work when I add it to the version? I really havent done anything else than copy and paste your code, but replace it with the HTML5_Notifier url and hash.

**Comment by JoshData** [comment]
Yeah I mean, it sounds like that should work. :) I'd have to try it out myself to see what's up.

**Comment by JoshData** [comment]
Thanks for your patience. Your changes actually worked fine for me, more or less. I made one more commit on top of this to finish it (8d9eb022d129664c1f2c6346fd13a3915962f395). Thanks!

**Pull request merged**
