### PR TITLE
bump ttl for ns records to 86400 as some registries require this

### PR DESCRIPTION
**Pull request by nordurljosahvida**
Fixes https://github.com/mail-in-a-box/mailinabox/issues/1381

### CODE REVIEW

**Comment by nordurljosahvida** [comment]
This should not be destructive in any way for other domain policies but I'd love some input to make absolutely sure no policies for other TLDs get infringed

**Comment by JoshData** [comment]
:+1: We'll leave this up for discussion for a bit. The change seems totally reasonable/fine to me. A one-day TTL for a NS record seem about right.

**Comment by hija** [comment]
I feel like 24h is quite high if you ever want to change your nameserver from MIAB to another one.
But from my point of view we don't really have a choice if we do not want to distinguish the TTLs between the different TLDs. Maybe that's something we could think about in the future (i.e. for .is domains a higher TTL than for others )... But for now it seems reasonable.

| Domain        | TTL        | 📫- Provider? |
|---------------|------------|--------------|
| google.com    | 5 minutes  | ✔            |
| yahoo.com     | 30 minutes |✔              |
| live.com      | 60 minutes |        ✔      |
| outlook.com   | 5 min      |             ✔ |
| aol.com       | 60 minutes |             ✔ |
| icloud.com    | 60 minutes |             ✔ |
| youtube.com   | 5 minutes  | ❌            |
| facebook.com  | 5 minutes  |      ❌        |
| amazon.com    | 60 seconds |        ❌      |
| wikipedia.org | 10 minutes |          ❌    |
| reddit.com    | 5 minutes  |           ❌   |
--> Checked with https://mxtoolbox.com/SuperTool.aspx
(Just considering US websites)

So with out 24h TTL we are definitely on the higher end of TTLs.

**Comment by thomae** [comment]
I get different results when querying SuperTool using the syntax dns:example.org:
Domain | NS Record TTL
------------- | -------------
google.com  | 4 days
yahoo.com  | 48 hrs
live.com  | 5 min
outlook.com  | 5 min
aol.com  | 48 hrs
icloud.com  | 24 hrs
youtube.com  | 4 days
facebook.com  | 48 hrs
amazon.com  | 60 min
wikipedia.org  | 24 hrs
reddit.com  | 48 hrs

**Comment by jvolkenant** [comment]
I have not had a problem with the current setting running MIAB the last few years.  DNS Lookups are cheap (low bandwith and low resources).  I would like a way to override this if possible. Perhaps in /etc/mailinabox.conf.

**Comment by hija** [comment]
> I get different results when querying SuperTool using the syntax dns:example.org:
> 
> Domain | NS Record TTL
> 
> ------------- | -------------
> 
> google.com  | 4 days
> 
> yahoo.com  | 48 hrs
> 
> live.com  | 5 min
> 
> outlook.com  | 5 min
> 
> aol.com  | 48 hrs
> 
> icloud.com  | 24 hrs
> 
> youtube.com  | 4 days
> 
> facebook.com  | 48 hrs
> 
> amazon.com  | 60 min
> 
> wikipedia.org  | 24 hrs
> 
> reddit.com  | 48 hrs

Well that's embarrassing 😀 I just checked again and did not notice that if you enter a new url (without specifying dns: in the beginning), it looks up the a record instead of the ns record. Don't know how I overlooked that yesterday. Thank's for pointing that out :)

**Comment by nordurljosahvida** [comment]
I don't think we need to distinguish by tld, i would simply make it 86400 by default and have a checkbox somewhere to "use low TTL for NS records [advanced - only use this if you know what it means and really need it]".

**Comment by anoma** [comment]
Is there ever really going to be a burning need for someone to require to make an unplanned sub 24h ns server change?

IMHO document this delay so users know to plan for it, change the TTL and push this.

**Comment by nordurljosahvida** [comment]
And if anything, to avoid cluttering the UI, make a script under `management` directory that simply lowers the TTL to 5 minutes, to give migrating users an option to prepare for the migration in advance.

**Comment by JoshData** [comment]
Thanks for the research everyone. Merging!

**Comment by nordurljosahvida** [comment]
Thanks!

**Comment by User1000001** [comment]
> Is there ever really going to be a burning need for someone to require to make an unplanned sub 24h ns server change?
> IMHO document this delay so users know to plan for it, change the TTL and push this.

As discussed [here](https://discourse.mailinabox.email/t/dyndns-does-not-update-one-subdomain/7687), I am the user with the burning need for sub 24h ns changes. I use Miab's custom dns api to forward a subdomain to my home server running Nextcloud, which gets a new IP every 24 hours. 
I have now temporarily fixed this problem by reverting the TTL to 1800 s. Since this change will be overwritten by the next update, I would really appreciate a permanent solution, e.g., by an entry in the mailinabox.conf. Should I try my luck with a pull request?

**Comment by JoshData** [comment]
The original issue was about NS records. You are probably talking about A/AAAA record. The fix probably applied to all records inadvertently.

I would accept a PR to make this configurable that way _if and only if_ you also write good documentation for it at https://github.com/mail-in-a-box/mailinabox.email/blob/master/maintenance.html.

**Comment by User1000001** [comment]
> I would accept a PR to make this configurable that way _if and only if_ you also write good documentation for it at https://github.com/mail-in-a-box/mailinabox.email/blob/master/maintenance.html.

I have now created a [pull request](https://github.com/mail-in-a-box/mailinabox/pull/1965) that hopefully fixes the problem. However, I don't believe that the maintenance guide is the right place to document this. From my point of view, two scripts in tools (something like `set_ttl_to_5_minutes.sh` and `set_ttl_to_1_day.sh`) would be better.

**Pull request merged**
