### PR TITLE
Make nsd listen on public instead of private addresses

### PR DESCRIPTION
**Pull request by eslindsey**
I'm not sure why #737 was closed, as it doesn't seem to have been resolved. This PR solves it but has only been tested on my own instance. Testing from others experiencing this problem would be welcome.

### CODE REVIEW

**Comment by eslindsey** [comment]
> The solution to your problem may simply be to change the value of PRIVATE_IPV6 to the address of the interface that you want local services to bind to.
I understand the issue more completely now, however this is still a bug. Based on what you're saying, MIAB should tell nsd to listen on *all* private addresses (in my case my box has 3 and one of them happens to be the same value as PUBLIC_IPV6 which is why this solution solved my problem). Instead, MIAB chooses only one—in my case, the wrong one. I will do some digging and see if I can figure out why $PRIVATE_IPV6 only contains the first IPv6 address, instead of all of them. Can you reopen the issue so I can correct it?

**Comment by JoshData** [comment]
It wasn't intended to bind to multiple addresses. Does it really need to? Or does it just need to bind to the correct one?

**Comment by eslindsey** [comment]
The correct one. So far my analysis of the problem is that my ISP's modem provides RA (SLAAC? I'm not sure of the difference) addresses, which my interface picks up 2 of. Meanwhile, the actual *assigned* static IPv6 is present as well. As far as I can tell, the modem's addresses are good for outbound only, as evidenced by them reaching the internet but failing to be reachable on DNS port. Meanwhile, the static I put on it works both ways. 

So, I can try and figure out how to disable the RA/SLAAC addresses, leaving only one route for the box to reach the internet, which should satisfy the existing heuristics. But that's kind of a band-aid more than a solution. It fixes it for me but not in general. 

A better but not perfect solution could be to have functions.sh compare the user-entered public IP against the machine's interfaces, and if it finds one prefer that over the machine's default route. Again, a band-aid but at least it would solve it for everyone (in this specific configuration).

I think the real problem here is that the *machine* is identifying "dynamic" addresses as preferred, instead of user-specified static ones. I haven't done enough digging to figure out how to change that, but if we can it would probably also fix MIAB.

**Comment by eslindsey** [comment]
Confirmed, adding `accept-ra: no` to `/etc/cloud/cloud.cfg.d/90-installer-network.cfg` *did* make the server refuse the extra addresses, bringing me down to just one public. MIAB then picked it up correctly. However, since machines are technically supposed to be able to handle multiple IPv6 addresses, this issue may arise again in the future.

**Pull request closed without merging**
