### PR TITLE
Document the "local" alias pointing to this box in Custom DNS

### PR DESCRIPTION
**Pull request by nikksno**
As per [this](https://github.com/mail-in-a-box/mailinabox/blob/master/management/dns_update.py#L211)

### CODE REVIEW

**Comment by JoshData** [comment]
Thanks. Some requests:

This should only show up when A/AAAA are selected. You can put this new text inside of the existing help that shows up for these record types below the field, which is stored a few lines lower.

Please put "local" in quotes so that it's clear it's meant to be written literally.

**Comment by nikksno** [comment]
Thanks, done.

**Comment by JoshData** [comment]
Thanks, merging!

**Comment by nikksno** [comment]
Awesome, thank you

**Pull request merged**
