### PR TITLE
postfix: reject_sender_login_mismatch prevents unauth emails to other miab users

### PR DESCRIPTION
**Pull request by jvolkenant**
I recommend adding reject_sender_login_mismatch to smtpd_sender_restrictions to prevent unauthenticated users from sending mail to other local miab users.

You are not able to relay mail through miab, which is perfect.  However, without reject_sender_login_mismatch, you are be able to spoof any email address (even those that do not exist) that is hosted by miab, and send it only to a local miab user.  Examples below:

This change can be made for master and ubuntu_bionic.

Install Prereqs needed to test
```
apt install libnet-ssleay-perl -y
wget http://www.jetmore.org/john/code/swaks/files/swaks-20170101.0/swaks
```
Test port 25 (some home Internet connections block port 25, we will also test 587 below)
```
root@m:~# perl swaks --to me@domainhostedonmiabserver.net --from emaildoesnotexist@domainhostedonmiabserver.net --server m.mymiabserver.com
=== Trying m.mymiabserver.com:25...
=== Connected to m.mymiabserver.com.
<-  220 m.mymiabserver.com ESMTP Hi, I'm a Mail-in-a-Box (Ubuntu/Postfix; see https://mailinabox.email/)
 -> EHLO testmachine.local
<-  250-m.mymiabserver.com
<-  250-PIPELINING
<-  250-SIZE 134217728
<-  250-VRFY
<-  250-ETRN
<-  250-STARTTLS
<-  250-ENHANCEDSTATUSCODES
<-  250-8BITMIME
<-  250 DSN
 -> MAIL FROM:<emaildoesnotexist@domainhostedonmiabserver.net>
<-  250 2.1.0 Ok
 -> RCPT TO:<me@domainhostedonmiabserver.net>
<** 450 4.2.0 <me@domainhostedonmiabserver.net>: Recipient address rejected: Greylisted, see http://postgrey.schweikert.ch/help/domainhostedonmiabserver.net.html
 -> QUIT
<-  221 2.0.0 Bye
=== Connection closed with remote host.
root@m:~# perl swaks --to me@domainhostedonmiabserver.net --from emaildoesnotexist@domainhostedonmiabserver.net --server m.mymiabserver.com
=== Trying m.mymiabserver.com:25...
=== Connected to m.mymiabserver.com.
<-  220 m.mymiabserver.com ESMTP Hi, I'm a Mail-in-a-Box (Ubuntu/Postfix; see https://mailinabox.email/)
 -> EHLO testmachine.local
<-  250-m.mymiabserver.com
<-  250-PIPELINING
<-  250-SIZE 134217728
<-  250-VRFY
<-  250-ETRN
<-  250-STARTTLS
<-  250-ENHANCEDSTATUSCODES
<-  250-8BITMIME
<-  250 DSN
 -> MAIL FROM:<emaildoesnotexist@domainhostedonmiabserver.net>
<-  250 2.1.0 Ok
 -> RCPT TO:<me@domainhostedonmiabserver.net>
<-  250 2.1.5 Ok
 -> DATA
<-  354 End data with <CR><LF>.<CR><LF>
 -> Date: Wed, 31 Oct 2018 09:03:37 -0700
 -> To: me@domainhostedonmiabserver.net
 -> From: emaildoesnotexist@domainhostedonmiabserver.net
 -> Subject: test Wed, 31 Oct 2018 09:03:37 -0700
 -> Message-Id: <20181031090337.005624@m.fireislandak.com>
 -> X-Mailer: swaks v20170101.0 jetmore.org/john/code/swaks/
 -> 
 -> This is a test mailing
 -> 
 -> .
<-  250 2.0.0 Ok: queued as 9AAC1280317
 -> QUIT
<-  221 2.0.0 Bye
=== Connection closed with remote host.
```
 Testing port 587 (requires STARTTLS)
```
root@pdxutil:/tmp# perl swaks --to me@domainhostedonmiabserver.net --from emaildoesnotexist@domainhostedonmiabserver.net --server m.mymiabserver.com:587 -tls
=== Trying m.mymiabserver.com:587...
=== Connected to m.mymiabserver.com.
<-  220 m.mymiabserver.com ESMTP Hi, I'm a Mail-in-a-Box (Ubuntu/Postfix; see https://mailinabox.email/)
 -> EHLO pdxutil.localdomain
<-  250-m.mymiabserver.com
<-  250-PIPELINING
<-  250-SIZE 134217728
<-  250-VRFY
<-  250-ETRN
<-  250-STARTTLS
<-  250-ENHANCEDSTATUSCODES
<-  250-8BITMIME
<-  250 DSN
 -> STARTTLS
<-  220 2.0.0 Ready to start TLS
=== TLS started with cipher TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256
=== TLS no local certificate set
=== TLS peer DN="/CN=m.mymiabserver.com"
 ~> EHLO pdxutil.localdomain
<~  250-m.mymiabserver.com
<~  250-PIPELINING
<~  250-SIZE 134217728
<~  250-VRFY
<~  250-ETRN
<~  250-AUTH PLAIN LOGIN
<~  250-ENHANCEDSTATUSCODES
<~  250-8BITMIME
<~  250 DSN
 ~> MAIL FROM:<emaildoesnotexist@domainhostedonmiabserver.net>
<~  250 2.1.0 Ok
 ~> RCPT TO:<me@domainhostedonmiabserver.net>
<~  250 2.1.5 Ok
 ~> DATA
<~  354 End data with <CR><LF>.<CR><LF>
 ~> Date: Wed, 31 Oct 2018 08:59:16 -0700
 ~> To: me@domainhostedonmiabserver.net
 ~> From: emaildoesnotexist@domainhostedonmiabserver.net
 ~> Subject: test Wed, 31 Oct 2018 08:59:16 -0700
 ~> Message-Id: <20181031085916.030040@pdxutil.localdomain>
 ~> X-Mailer: swaks v20170101.0 jetmore.org/john/code/swaks/
 ~> 
 ~> This is a test mailing
 ~> 
 ~> .
<~  250 2.0.0 Ok: queued as C47DD280317
 ~> QUIT
<~  221 2.0.0 Bye
=== Connection closed with remote host.
```

### CODE REVIEW

**Comment by JoshData** [comment]
Hi. Thanks.

See https://github.com/mail-in-a-box/mailinabox/pull/427 for some history. This could be done by actually just changing `reject_authenticated_sender_login_mimatch` to `reject_sender_login_mimatch` instead of adding it.

But the reason I think we haven't done it is that while Mail-in-a-Box assumes for some purposes -- mostly DNS -- that it is the only server permitted to send mail for the domains it is serving, it isn't a hard requirement. If a user is setting their own DNS records or has a more complicated setup, there may be other servers producing mail for the domains --- in which case, the Mail-in-a-Box should accept it.

**Comment by lorrin** [comment]
I briefly tried changing `reject_authenticated_sender_login_mismatch` to `reject_known_sender_login_mismatch` (which I think is strictly more permissive than `reject_sender_login_mismatch`), and bumped into problems with the daily_tasks not being able to deliver their output.
{{{
From: root@miab.my.domain (Cron Daemon)
To: root@miab.my.domain
Subject: Cron <root@miab> (cd /root/mailinabox && management/daily_tasks.sh)
Date: Tue, 20 Nov 2018 03:00:18 -0800 (PST)

Traceback (most recent call last):
  File "management/email_administrator.py", line 59, in <module>
    msg.as_string())
  File "/usr/lib/python3.4/smtplib.py", line 797, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'administrator@miab.my.domain': (553, b'5.7.1 <administrator@miab.my.domain>: Sender address rejected: not logged in')}
}}}

**Comment by jvolkenant** [comment]
I can't say I've tested "reject_known_sender_login_mismatch", only "reject_sender_login_mismatch"

This is why "reject_known_sender_login_mismatch" isn't working:

Looking at http://www.postfix.org/postconf.5.html

"reject_known_sender_login_mismatch
    Apply the reject_sender_login_mismatch restriction only to MAIL FROM addresses that are known in $smtpd_sender_login_maps. This feature is available in Postfix version 2.11 and later. "

Check the sqlite query in smtpd_sender_login_maps=sqlite:/etc/postfix/sender-login-maps.cf,  when I tested my administrator@m.domain.com, it did not return administrator@m.domain.com as a permitted_sender.

Instead of reject_known_sender_login_mismatch, could you try reject_sender_login_mismatch since they behave differently?

**Comment by jvolkenant** [comment]
Changed to using reject_sender_login_mismatch
Added permit_mynetworks so we can send mail from the miab itself without getting what @lorrin experienced above


Additionally we need smtpd_sasl_auth_enable = yes so sasl looks work on port 25; such that reject_sender_login_mismatch works at all.

**Comment by JoshData** [comment]
Turning SASL back on on port 25 is not an option for the reason described in the comment you took out --- it creates another problem. Plus for the reasons I said earlier, this would probably break things for some people.

However, I see the security value in not allowing incoming spoofed messages.

**Comment by jvolkenant** [comment]
Yea I understand the concern.  Postfix in 18.04 seems to require SASL being on to do this check.  It was not a requirement in 14.04.  I still think it would be good to decline mail for domains we host that come to us from other MTA's without the changes of this PR, I just haven't found what that change would be yet.

**Pull request closed without merging**
