### PR TITLE
Added a warning to the installation / setup script

### PR DESCRIPTION
**Pull request by s4wny**
See pull request #638 and issue #635 for more information.

### CODE REVIEW

**Comment by JoshData** [comment]
Simple and pretty clear. Thanks.

Did you give this PR a real-life test?

**Comment by s4wny** [comment]
Yes. proof

Tested on a Ubuntu 14.04.3 x64 machine.

**Comment by JoshData** [comment]
Thanks. Just noticed that in the second "Mail-in-a-Box" the b should be capitalized. Can you revise?

**Comment by s4wny** [comment]
Opps, fixed it.

**Comment by JoshData** [comment]
Merged, thanks!

**Pull request merged**
