### PR TITLE
Added a replacement script for the mail_log.py management script

### PR DESCRIPTION
**Pull request by biermeester**
This replacement script is based on `mail_log.py`, but has a few improvements:
- Command line arguments that allow you to control what is scanned and displayed.
- The ability to select a time span to scan.
- Log files are scanned from end to beginning to limit the number of lines that need to be read
- Gzipped log files can be scanned too, if needed.
- Date parsing for the log lines has been replaced with less smart, but much faster code.
- Some regular expressions have been fixed (Were probably broken due to changes in log formats)
- Just run `maillogscan.py -h` for more information.

There are still some improvements needed and I have some ideas on how to use this script for monitoring purposes, but that's something for later.

### CODE REVIEW

**Comment by JoshData** [comment]
Neat thanks!

**Comment by yodax** [comment]
I played around with this a bit, very nice! It eliminates the need for grep'ing the mail log most of the time. (I haven't reviewed the code extensively)

**Comment by biermeester** [comment]
I had to make a little tweak, because I suddenly have some old September dates in my log in between the current October dates. 


>Oct  7 10:04:02 herald postfix/smtpd[23186]: lost connection after RCPT from unknown[xxxx]
>
>Oct  7 10:04:02 herald postfix/smtpd[23186]: disconnect from unknown[xxxxx]
>
>Sep 30 02:00:15 herald postfix/tlsmgr[23196]: message repeated 5 times: [ tlsmgr_cache_run_event: start TLS smtp session cache cleanup]
>
>Oct 07 10:05:30 imap-login: Info: Login: user=<xxxxxx>, method=PLAIN, rip=xxxxxx, lip=cccccc, mpid=23690, TLS, session=<Apm030E+HABQc0kn>`

**Comment by yeah** [comment]
I am getting this when I try it out. I haven't had time to debug any further. Maybe this makes sense to you @biermeester?

```shell
root@m:~/mailinabox# python3 management/mail_log.py
Scanning from 2017-03-27 06:47:10 back to 2017-03-27 00:00:00
Processing file /var/log/mail.log ...
27139 Log lines scanned, 7444 lines parsed in 0.28 seconds


Sent email between 2017-03-27 00:00:00 and 2017-03-27 06:47:10
Traceback (most recent call last):
  File "management/mail_log.py", line 881, in <module>
    scan_mail_log(env_vars)
  File "management/mail_log.py", line 142, in scan_mail_log
    print_header(msg.format(END_DATE, START_DATE))
  File "management/mail_log.py", line 798, in print_header
    print("\u2550" * len(msg), '\n')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-61: ordinal not in range(128)
```

Maybe I'm also holding it wrong?

**Comment by biermeester** [comment]
Hmm, it's trying to print a unicode character (http://www.fileformat.info/info/unicode/char/2550/index.htm). What encoding are you using on your terminal? (i.e. what does running `echo $LANG` or `locale charmap` show you?)

**Comment by yeah** [comment]
Nevermind, I ran into [this](https://sskaje.me/2014/01/lc-ctype-issue/) locally. Nothing to do with `mail_log.py`.

**Pull request closed without merging**
