### PR TITLE
Fully working docker!

### PR DESCRIPTION
**Pull request by milani**
I used this branch to setup mailinabox inside docker and it works like a charm.

### CODE REVIEW

**Comment by JoshData** [comment]
Wow!

**Comment by jmeyo** [comment]
Hi, 
Are you going to merge this branch in master, or we should stay on the branch ?

**Comment by JoshData** [comment]
We'll stay on the branch until it works. (It's not working for me, although it's much closer now.)

**Comment by milani** [comment]
@JoshData I think you have another problem not related to docker. I'm using two instances of this branch in production on a single box and it works like a charm, handling hundreds of mails a day.

**Comment by JoshData** [comment]
What version of Docker are you running?

**Comment by milani** [comment]
I'm running on

* Ubuntu 14.04 x64
* Docker version 1.4.1, build 5bc2ff8

**Comment by JoshData** [comment]
Okay. I had stock Ubuntu 14.04 docker installed. Trying now with the latest.....

**Comment by finid** [comment]
@milani, considering the RAM requirements of the application, hwo much RAM do you have on the host OS? How much is allocated to the Docker Container?

**Comment by milani** [comment]
@finid It is hard to determine how much memory docker instance is using as the processes are shared with host and I have other processes running. The host has a 2GB RAM. It seems processes running inside docker consume less than 20% of memory all together.

**Comment by finid** [comment]
So if it's running smoothly inside Docker and Docker is chewing up about 20% RAM on a 2 GB box, that's considerable less than the recommended 1 GB of RAM. 

Good to know, and thanks.

**Comment by milani** [comment]
@finid you should notice that I'm reporting current consumption, pick-time may be very different. And docker does not affect performance or utilization. Docker is just a tool to manage chroots!

**Comment by JoshData** [comment]
I was able to simplify a lot on my docker branch: https://github.com/mail-in-a-box/mailinabox/commit/docker

Seems like any services with sysvinit-compatible scripts (everything but Dovecot) is actually working without needing any special runit script.

**Comment by blackrosezy** [comment]
@milani This tool can show a quick overview of your containers usage.
```
$ pip install glances
$ glances
```

**Pull request merged**
