### PR TITLE
Apply small Nextcloud upgrade to 26.0.13

### PR DESCRIPTION
**Pull request by binarykitchen**
Here's the tested, low-hanging fruit, as communicated in:
- https://github.com/mail-in-a-box/mailinabox/issues/2400
- [mailinabox.slack.com/archives/C09E3L9KM/p1718674416382599](https://mailinabox.slack.com/archives/C09E3L9KM/p1718674416382599)

Tested and updated the hash checksums. Just a very minor upgrade before we make the next big upgrade ...

### CODE REVIEW

**Review by dms00 — APPROVED** [review]

**Comment by binarykitchen** [comment]
Thanks @dms00 - before I merge, @JoshData, tell me, when is the next release scheduled?

**Comment by JoshData** [comment]
If we merge this this week, I'll probably do a release the following week (July 8+).

**Comment by binarykitchen** [comment]
Good. In that case, end of this week, will rebase with the latest master and test everything all over again.

**Comment by binarykitchen** [comment]
Tested again and all looks good. Ready to be merged @JoshData

**Pull request merged**
