### PR TITLE
Update status_checks.py

### PR DESCRIPTION
**Pull request by CholoTook**
Switching to a more robust way of checking for PasswordAuthentication

### CODE REVIEW

**Comment by CholoTook** [comment]
This function uses the subprocess.run method to execute the sshd -T command, which prints the effective configuration of the SSH server, and then checks if 'passwordauthentication yes' is present in the output. If there's an error executing the command (like if sshd isn't found), it will print an error message. If the command runs but the configuration allows password authentication, it will print an error with instructions on how to secure the SSH server. Otherwise, it will confirm that password-based login is disabled.

**Comment by dashrb** [comment]
I saw this bug too (in an AWS EC2 instance where sshd is configured using more sshd_conf.d/* files), and even worked up a solution on my own (slightly differently).

But I notice in your code you've changed the behavior slightly: if sshd is NOT installed, the original code does a simple "return"; in contrast, yours prints an error message to the user.

**Comment by JoshData** [comment]
There was a similar issue getting the SSH port. Both are addressed in #2330, so I'm closing this PR. Thanks.

**Comment by dbolser** [comment]
Thanks both

**Pull request closed without merging**
