### PR TITLE
Fix always creating full backups when rsyncing

### PR DESCRIPTION
**Pull request by durd**
With the row uncommented backup.py always creates full backups and rsyncs them to the destination configured.
Commented away, backup.py returns to normal and creates incremental backups.

~~_However_, listing on webgui is still broken.~~
CLI --list and --status now also works.

This is my first ever pull request, I'm no developer except for quick and dirty (shows in the pull request...). Also it's only fixing the issue by 75%, fixing incremental backups. ~~I've got no idea about the webgui.~~

Edit:
A reboot actually fixed the webgui listing.

### CODE REVIEW

**Comment by durd** [comment]
Just noticed that --verify is still broken:
```
*snip*
Processed volume 4 of 4
Verify complete: 81463 files compared, 2 differences found.
Traceback (most recent call last):
  File "mailinabox/management/backup.py", line 532, in <module>
    run_duplicity_verification()
  File "mailinabox/management/backup.py", line 350, in run_duplicity_verification
    ] + rsync_ssh_options, get_env(env))
  File "/home/toe/mailinabox/management/utils.py", line 123, in shell
    ret = getattr(subprocess, method)(cmd_args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/duplicity', '--verbosity', 'info', 'verify', '--compare-data', '--archive-dir', '/home/user-data/backup/cache', '--exclude', '/home/user-data/backup', 'rsync://toe@ftp.durd.net//backups/mail.durd.net', '/home/user-data', '--rsync-options=-e "/usr/bin/ssh -oStrictHostKeyChecking=no -oBatchMode=yes -p 22 -i /root/.ssh/id_rsa_miab"']' returned non-zero exit status 1.
```

**Comment by durd** [comment]
Just noticed that --verify is still broken:
```
*snip*
Processed volume 4 of 4
Verify complete: 81463 files compared, 2 differences found.
Traceback (most recent call last):
  File "mailinabox/management/backup.py", line 532, in <module>
    run_duplicity_verification()
  File "mailinabox/management/backup.py", line 350, in run_duplicity_verification
    ] + rsync_ssh_options, get_env(env))
  File "/home/toe/mailinabox/management/utils.py", line 123, in shell
    ret = getattr(subprocess, method)(cmd_args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/duplicity', '--verbosity', 'info', 'verify', '--compare-data', '--archive-dir', '/home/user-data/backup/cache', '--exclude', '/home/user-data/backup', 'rsync://toe@ftp.durd.net//backups/mail.durd.net', '/home/user-data', '--rsync-options=-e "/usr/bin/ssh -oStrictHostKeyChecking=no -oBatchMode=yes -p 22 -i /root/.ssh/id_rsa_miab"']' returned non-zero exit status 1.
```

**Comment by jvolkenant** [comment]
Looks like "-i /root/.ssh/id_rsa_miab" is added to the duplicity --verify error above.

Maybe the proposed fix to #1572 might affect some of this functionality?

**Comment by jvolkenant** [comment]
> 
> 
> Just noticed that --verify is still broken:
> 
> ```
> *snip*
> Processed volume 4 of 4
> Verify complete: 81463 files compared, 2 differences found.
> Traceback (most recent call last):
>   File "mailinabox/management/backup.py", line 532, in <module>
>     run_duplicity_verification()
>   File "mailinabox/management/backup.py", line 350, in run_duplicity_verification
>     ] + rsync_ssh_options, get_env(env))
>   File "/home/toe/mailinabox/management/utils.py", line 123, in shell
>     ret = getattr(subprocess, method)(cmd_args, **kwargs)
>   File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['/usr/bin/duplicity', '--verbosity', 'info', 'verify', '--compare-data', '--archive-dir', '/home/user-data/backup/cache', '--exclude', '/home/user-data/backup', 'rsync://toe@ftp.durd.net//backups/mail.durd.net', '/home/user-data', '--rsync-options=-e "/usr/bin/ssh -oStrictHostKeyChecking=no -oBatchMode=yes -p 22 -i /root/.ssh/id_rsa_miab"']' returned non-zero exit status 1.
> ```

The command "failed" (had a non-zero exit code) because there were "2 differences found".  From http://duplicity.nongnu.org/duplicity.1.html
```
verify [--compare-data] [--time <time>] [--file-to-restore <rel_path>] <url> <local_path>
    Restore backup contents temporarily file by file and compare against the local path’s contents
    duplicity will exit with a non-zero error level if any files are different.
    On verbosity level info (4) or higher, a message for each file that has changed will be logged. 
```

Ideally this would always occur as files (at some point) will be different from /home/user-data and the last backup. I think it should not be thought of an an error.  There should be some clarification of this when the command is run however.

**Comment by jvolkenant** [comment]
I'm testing your patch and will reply after it does some incremental's.  It also fixes other issues where the id_rsa key is copied to the destination.

Related issues: #1508 #1511 #1572

**Comment by jvolkenant** [comment]
> 
> 
> Looks like "-i /root/.ssh/id_rsa_miab" is added to the duplicity --verify error above.
> 
> Maybe the proposed fix to #1572 might affect some of this functionality?

This patch fixes #1572 as well.

**Comment by durd** [comment]
> This patch fixes #1572 as well.

Kinda liked having the private key backed up automatically, in case I forgot or ignored the instructions. But I can see the security issue with that.

Glad my patch works and fixes other issues.

**Comment by steadfasterX** [comment]
thanks for this PR, will test it as well the next days

**Comment by durd** [comment]
This issue was fixed in a commit to v0.43, I'm therefore closing this pull-request.

**Pull request closed without merging**
