### PR TITLE
softer the greylisting delay restriction

### PR DESCRIPTION
**Pull request by Xoib**
A lot of legit mail server try again between 200 and 285 seconds, then 3 hours later. Why ? RFC is not strict about retry timer so postfix and other MTA have their own intervals.
To fix the problem of receiving these e-mail really latter, I reduced the delay of postgrey to 180 seconds (default is 300 seconds).

Discussion: https://discourse.mailinabox.email/t/sometime-e-mail-come-3h30-later-to-the-mailbox/484

### CODE REVIEW

**Comment by JoshData** [comment]
Fantastic. Thanks. Would you mind revising the PR to include your explanation above in a comment block above that line?

**Comment by Xoib** [comment]
I did a new commit. Maybe you meant a rebase on 2b5b2b0 ?

**Comment by JoshData** [comment]
So I actually mean a comment in `setup/mail-postfix.sh` itself (i.e. on lines with `#`-marks), so the explanation is close to where the option is set. Adding the explanation to the commit message too is great.

**Comment by Xoib** [comment]
Oh yeah of course, thanks for the remark. It's done. Let me know if there is anything else.

**Comment by JoshData** [comment]
Merged!

**Comment by JoshData** [comment]
Unmerged! See @squeezy80's comments at https://github.com/mail-in-a-box/mailinabox/commit/cd15d9e1b67e45ad6cfeff1297bb6a435aab3544#commitcomment-11267356. Please test and try again. :)

**Comment by Xoib** [comment]
Ok, I am looking into it.

**Pull request merged**
