### PR TITLE
Add support for NS records in custom domains

### PR DESCRIPTION
**Pull request by ctrlaltdel**
This feature comes handy in case where your custom dns zone has a subzone delegated to other dns server.

### CODE REVIEW

**Comment by guyzmo** [comment]
might need a bit of explaination in the documentation though, explaining that you shall not change the DNS of the main domain. Or forbid the change of primary DNS of the main domain.

**Comment by JoshData** [comment]
It should also ensure that an invalid value can't be submitted, since that'll break `nsd` and everything will stop working.

**Comment by guyzmo** [comment]
well, the only way would be to validate using nsd check, but that works as well with any other value, wouldn't it?

**Comment by JoshData** [comment]
No, we can know ahead of time if it is a valid value or not.

**Comment by ctrlaltdel** [comment]
@guyzmo and @JoshData thanks for the comments!

What do you think of this new code?

**Comment by JoshData** [comment]
Nice.

a) You could even move the qname test up so that it applies to all record types, since all record types require a valid qname. (But other record types should allow an empty qname.)

b) And you could use the same value test for CNAME too. So it'd be handy to fix that while you're there.

c) But check that trailing dots are handled correctly. NS and CNAME records both typically end with a `.`, otherwise the domain name is interpreted relative to the zone. It's weird legacy behavior in how DNS zone files work that trips up most people - there are questions in our issues or forum from people that have missed that. You could simply always add a `.` to the value for NS and CNAME so that users don't have to worry about it. (If you don't add the `.`, then the value test must accept values that end in dots.)

So if you wouldn't mind addressing all three issues, we'll be good to go here.

**Comment by ctrlaltdel** [comment]
@JoshData all points have been addressed in the last commit as well as a bug in the empty qname test which should actually be `qname == zone` instead of `qname == ""`.

**Comment by JoshData** [comment]
Looks great, although by "leading" you mean "trailing" in the comments.

If anyone else reading can give this PR a test, that'd save me some time. Thanks.

**Comment by yodax** [comment]
I have tested the following:

- [X] Set NS on primary domain, this wasn't allowed:
schermafbeelding 2017-06-11 om 11 17 05

- [X] On a secondary domain:

```
$ dig @kroes.space test.kroes.space NS

; <<>> DiG 9.8.3-P1 <<>> @kroes.space test.kroes.space NS
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44797
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;test.kroes.space.		IN	NS

;; AUTHORITY SECTION:
test.kroes.space.	1800	IN	NS	test.kroes.test.

;; Query time: 36 msec
;; SERVER: 163.172.133.32#53(163.172.133.32)
;; WHEN: Sun Jun 11 11:19:06 2017
;; MSG SIZE  rcvd: 63
```
- [X] With an invalid address:
schermafbeelding 2017-06-11 om 11 24 09

**Comment by JoshData** [comment]
Thanks all.

**Pull request merged**
