### PR TITLE
Autodiscovery fix for additional hosted email domains, Fixes #941

### LINKED ISSUE #941: Thunderbird Autoconfiguration
I'm trying to setup Thunderbird [autoconfiguration](https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration). This requires an XML file hard coded at this path: `/mail/config-v1.1.xml`. When I try to make a new domain (`autoconfig.mail.domain.com`) and point it to my box (as well as adding the appropriate alias and creating the directory through the web interface). If I create a `mail` folder in `autoconfig.mail.domain.com` and try to access the index page (`autoconfig.mail.domain.com/mail`) I am taken to Roundcube. This would normally be appropriate if I just used `domain.com/mail`, but as I am using another subdomain, it shouldn't be using the Roundcube stuff.

Is there any way I can add this configuration file?

### PR DESCRIPTION
**Pull request by jvolkenant**
Autodiscovery problems exist for email domains added in addition to the first domain used for setup. This problem exists for both Thunderbird lookup, as well as ActiveSync Autodiscovery.

For example,  If we setup a MIAB at box.example.com.  Thunderbird autoconfig will work because MIAB already hosts the config here https://example.com/.well-known/autoconfig/mail/config-v1.1.xml.  ActiveSync Autodiscovery will work because MIAB already hosts https://example.com/Autodiscover/Autodiscover.xml

This patch fixes the following problem. On the same example MIAB server, I setup otherdomain.com for email, but I don't host my website there.  https://otherdomain.com/.well-known/autoconfig/mail/config-v1.1.xml is never found since the A record points somewhere else.  Thunderbird will then try https://autoconfig.otherdomain.com/mail/config-v1.1.xml. Currently that file (and associating dns record) is not configured, and in this scenario Thunderbird would need to be configured Manually.

ActiveSync Autodiscovery fails as well, https://otherdomain.com/Autodiscover/Autodiscover.xml runs into the same problem.

Lucky for us both Thunderbird and ActiveSync Autodiscovery will check additional URL's during its search for auto information.

This patch adds CNAME entries to make autoconfig.otherdomain.com and autodiscover.otherdomain.com entries with dns_update.  (It will technically make all non PRIMARY_HOSTNAME domains have a CNAME ENTRY). As well as a nginx config posted on #941.

This patch gives us the additional Thunderbird lookup at https://autoconfig.otherdomain.com/mail/config-v1.1.xml.  For ActiveSync Autodiscovery, the path https://autodiscover.otherdomain.com/Autodiscover/Autodiscover.xml is a 302 redirect to https://box.example.com/Autodiscover/Autodiscover.xml.

Testing:
Thunderbird:  Test with Thunderbird for an email that is in addition to the domain used to setup MIAB.
Activesync Autodiscover: [Microsoft Remote Connectivity Analyzer](https://autodiscover.otherdomain.com/Autodiscover/Autodiscover.xml) or any Activesync App, I tested Nine on Android.

The only better way I can see would be to add the nginx edit 0e69c5e, but instead of CNAME, we would generate SSL certs instead for autoconfig. and autodiscover. for every domain.  But the CNAME seems to work from what I've tested.

### CODE REVIEW

**Comment by JoshData** [comment]
Nice work.

**Comment by JoshData** [comment]
Hey.

What's happening with TLS with this patch? With a CNAME the clients will resolve the autodiscover subdomains but the TLS certificate won't be valid for it because we're not provisioning TLS certificates for them, right? The clients should show a TLS error.

We might also want to revise the nginx config to explicitly handle those domains, otherwise nginx is probably just falling back to the primary hostname because the autodiscover subdomains aren't otherwise handled.

**Comment by jvolkenant** [comment]
Although autoconfig/autodiscover is working with the patch, the primary hostname cert is what is being used.  I'll have to dig into how to add autodiscover... and autoconfig... to the list of certs to request.

**Comment by jvolkenant** [comment]
I see 3 methods to handle this problem.

Method 1 from this PR (Above):
CNAME autodiscover&autoconfig to PRIMARY_HOSTNAME, seems to work, but the wrong certs are served.

Method 2 from this PR (https://github.com/jvolkenant/mailinabox/tree/client_autoconfig_fixes_method2):
Handle autodiscover&autcoconfig like www, however with autodiscover&autoconfig we don't redirect to the base domain, we always redirect to PRIMARY_HOSTNAME (in case base domain is hosted elsewhere like it is in my case)  We can provision ssl certs and via a series of 301's, we can do both Thunderbird and AutoSync Setup.

Method 3, still needs a PR (if its decided this method is best):
Provision autodiscover&autoconfig SSL's, but instead of 301 to PRIMARY_HOSTNAME, we just serve it directly (with conf/nginx-alldomains.conf)

**Comment by JoshData** [comment]
I like 3. :)

**Comment by jvolkenant** [comment]
Back to the drawing board :)

**Comment by jvolkenant** [comment]
#1196 should be related to this

**Comment by jvolkenant** [comment]
I updated the PR such that the autoconfig/autodiscover subdomains are added to the domains list.  You can now provision ssl certificates for those domains and they will serve with correct SSL certs.

**Comment by jvolkenant** [comment]
On my existing 14.04 box, I was able to provision ssl certs for the new A records, but on 18.04 I don't get the button at the top to provision the new certs, not sure if its related to this PR or just ubuntu_bionic.

**Comment by jvolkenant** [comment]
So, I ended up just enabling autoconfig/autodiscover records for all mail domains.  So if there is an email address configured, it should have an autoconfig/autodiscover record now.

**Comment by ringe** [comment]
I'm going to test this patch now

**Comment by ringe** [comment]
I patched this PR onto the current master branch and is running a full live test at my former mailserver IP address. Thunderbird found the setup right away. Outlook mobile was still asking for which server and username to use, but found the email address to belong to an Exchange server. Meaning it found ActiveSync. Outlook desktop didn't figure it out automatically and had to be told it was an IMAP server and I had to type the password again. Couldn't get the calendar up on Outlook desktop.

I consider this a success. I recommend merging the PR.

**Comment by jvolkenant** [comment]
> 
> 
> I patched this PR onto the current master branch and is running a full live test at my former mailserver IP address. Thunderbird found the setup right away. Outlook mobile was still asking for which server and username to use, but found the email address to belong to an Exchange server. Meaning it found ActiveSync. Outlook desktop didn't figure it out automatically and had to be told it was an IMAP server and I had to type the password again. Couldn't get the calendar up on Outlook desktop.
> 
> I consider this a success. I recommend merging the PR.

Did you go to the "TLS (SSL) Certificates" and get the autodiscover.* and autoconfig.* certs after adding the PR?

I've never known that Outlook works with Activesync & Z-Push (or at least I've never got it to work).  Activesync and iPhone/Android phone apps should work fine (it does with Google and Nine on Android for me as well as the https://testconnectivity.microsoft.com test "Exchange Activesync Autodiscover" test) as well as Thunderbird IMAP setup as worked fine for me with this patch (Thunderbird Calendar and Contacts setup is a manual process (always has been)).

**Comment by ringe** [comment]
Yes I did deploy TLS. Worked like a charm.
You just confirmed what I saw in my test.

Merge, please. 😅


Den 9. mai 2019 17:50:13 CEST, skrev jvolkenant <notifications@github.com>:
>> 
>> 
>> I patched this PR onto the current master branch and is running a
>full live test at my former mailserver IP address. Thunderbird found
>the setup right away. Outlook mobile was still asking for which server
>and username to use, but found the email address to belong to an
>Exchange server. Meaning it found ActiveSync. Outlook desktop didn't
>figure it out automatically and had to be told it was an IMAP server
>and I had to type the password again. Couldn't get the calendar up on
>Outlook desktop.
>> 
>> I consider this a success. I recommend merging the PR.
>
>Did you go to the "TLS (SSL) Certificates" and get the autodiscover.*
>and autoconfig.* certs after adding the PR?
>
>I've never known that Outlook works with Activesync & Z-Push (or at
>least I've never got it to work).  Activesync and iPhone/Android phone
>apps should work fine (it does with Google and Nine on Android for me
>as well as the https://testconnectivity.microsoft.com test "Exchange
>Activesync Autodiscover" test) as well as Thunderbird IMAP setup as
>worked fine for me with this patch (Thunderbird Calendar and Contacts
>setup is a manual process (always has been)).  
>
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/mail-in-a-box/mailinabox/pull/1467#issuecomment-490960335

-- 
Sendt fra min Android-enhet med K-9 e-post. Unnskyld min kortfattethet.

**Comment by JoshData** [comment]
Thanks everyone!

**Pull request merged**
