### PR TITLE
Upgrade NextCloud to 13.06

### PR DESCRIPTION
**Pull request by yodax**

### CODE REVIEW

**Comment by draft13** [comment]
Isn't 14.01 the latest stable?

**Comment by yodax** [comment]
It is, well do that after the Ubuntu upgrade.

**Comment by JoshData** [comment]
Update the CHANGELOG.md please? Thanks.

**Comment by yodax** [comment]
Changelog updated per @JoshData request 😄 You'd think that after all the PR's I would remember it by now.

**Comment by JoshData** [comment]
:) Merged

**Pull request merged**
