### PR TITLE
Improvements of message boxes (Installation of Mail-in-a-Box)

### PR DESCRIPTION
**Pull request by aspdye**
-Added Information about the fact, that the machine should be dedicated to MiaB. (#635)
-Added Warning (WARNING: Your servers configuration and customization will be overwritten.)
-Added a Note that you can find informations about the software, the license etc. under https://mailinabox.email ;)
-Make it clear, what you can change by running "sudo mailinabox" (hostname and setup configuration)

### CODE REVIEW

**Comment by JoshData** [comment]
Thanks but this is far too scary for novices. People who are following the directions should not be alarmed.

**Comment by aspdye** [comment]
Do you have an better formulation :sweat_smile:

**Comment by dhpiggott** [comment]
What about a test like the one at https://github.com/mail-in-a-box/mailinabox/blob/834c42bc503b3430eb8100343581ed3be396c41b/setup/web.sh#L10, except putting it in place of the lines you added in this PR and making a dialog show if apache2 does exist?

**Comment by alexweissman** [comment]
@dhpiggott that is more like what I was hoping to see.  Something that explicitly warns when it is about to remove something (such as Apache), and then prompts the user to confirm.

**Comment by JoshData** [comment]
Removing apache is like one of a dozen things that Mail-in-a-Box could screw people up with.

**Comment by alexweissman** [comment]
Ok, that's fair.  In that case, maybe @aspdye's original idea of warning before installation begins would be the best course.  

But, I think it would still be good to mention Apache in that warning, in particular.  It will be a very common case where someone sets up their LAMP stack on VPS for the first time, realizes that they still need a mail solution, and then finds MiaB (which is the perfect solution to scalable email once you leave the world of cpanel shared hosting).

Help a (former) DC brother out ;-)

**Comment by aspdye** [comment]
Or maybe we just give the warning: Read the Instructions on mailinabox.email first!

**Comment by alexweissman** [comment]
Ha!  I've found, for warnings to work, you really have to shove them in peoples' faces.

**Comment by aspdye** [comment]
But somebody Running an own Server - should be able to read Instructions ;)
I know that MiaB is an Zero-Knowledge-Product, but i think you should have enough background to read the manual. :laughing:

**Comment by alexweissman** [comment]
I usually read the manual to figure out what *to* do, not what *not* to do.

**Comment by bronson** [comment]
Maybe just add a new question?

"Hi, are you installing this on a brand new Ubuntu installation dedicated to Mail-in-a-Box?"  Yes/No

If they click no, THEN they get hit with the scary text.

**Comment by JoshData** [comment]
That sounds good. If the user chooses no, setup stops. This should only appear on first installation (/etc/mailinabox.conf not present). And it must be written in a way that novice users will be able to identify the correct answer easily and without stress.

**Comment by JoshHarmon** [comment]
I'm sorry for nitpicking on grammar, but there are several errors that shouldn't be released.

> Please keep in mind, that you should use an machine, which is dedicated for mail-in-a-box

should be

> Please keep in mind that you should use a machine which is dedicated for Mail-in-a-Box

The middle part of the sentence is not a separate clause, not a valid use of apostrophe (referring to a noun that is not present), and not a location where a pause in speaking or reading makes sense. Further, the `which` clause is essential, due to `machine` not referring to a specific machine that the audience is already familiar with. Additionally, the M and B should be capitalized in MiaB.

> WARNING: Your servers configuration and customization will be overwritten.

should be

> WARNING: Your server's configuration and customization will be overwritten.

assuming that you intend to use a personal tone (which is fine; Josh started it that way) and want to use the possessive form of `server`. As it is, the plural form of `server` suggests that a _single_ configuration of multiple servers will be overwritten, which can be argued to be correct in a way (depending on if you work from a server being defined as a software package sending and receiving information, or if it is to be defined as the physical "box"--or VM--that hosts multiple services), but I contend that using the possessive form of `server` would fit most appropriately.

> For more information about the software itself, how it works and the License visit 

should be at least

> For more information about the software itself, how it works and the License, visit 

However, I tend to strongly prefer Oxford commas in situations like this because you are constructing a list of things that users can find more information about, including `the software itself`, `how it works`, and `the License`. I, personally, would add a comma between `works` and `and`.

The comma before visit is necessary because `For more information about [LIST]` is an independent clause, `visit` is the verb of the matching independent clause, **and** `visit` is the action that you want users to perform if they want more information. The overall sentence is an imperative sentence with `For...` defining the circumstances in which a user should `visit`.

**Comment by aspdye** [comment]
You are totaly right, and i think we would not release it in my (verry concept) way of bad grammar :laughing: 
I will correct this, but i dont know if we going to release this anyway. But thank you for you Commit :smile:

**Comment by JoshData** [comment]
Fixed by #712 instead.

**Pull request closed without merging**
