### PR TITLE
Fixes #309, removed hardcoded /home directory to apply the existing config

### LINKED ISSUE #309: Changing STORAGE_ROOT has no effect.
What is the purpose of this condition?
```bash
if [ -f /etc/mailinabox.conf ]; then
    # Run any system migrations before proceeding. Since this is a second run,
    # we assume we have Python already installed.
    setup/migrate.py --migrate
    # Load the old .conf file to get existing configuration options loaded
    # into variables with a DEFAULT_ prefix.
    cat /etc/mailinabox.conf | sed s/^/DEFAULT_/ > /tmp/mailinabox.prev.conf
    source /tmp/mailinabox.prev.conf
    rm -f /tmp/mailinabox.prev.conf
fi
```
[curious if block](https://github.com/mail-in-a-box/mailinabox/blob/master/setup/start.sh).

Let's say I have a partitoned box, with plenty of gb's on /var and very less on /. So all I wanna do is to change the STORAGE_ROOT to /var.

I've install mailinabox to /home/user-data. Then I stop the daemon `service mailinabox stop`. Move all files to /var. Change the `/etc/mailinabox.conf` file, especially the `STORAGE_ROOT` var. And re-run the installation script `mailinabox`. Nothings happend, everthing is installed to `/home/`.

Why? I think all my settings in the  `/etc/mailinabox.conf` file got lost. Cause my `STORAGE_ROOT` var was renamed to `DEFAULT_STORAGE_ROOT` and then sourced. But miab never ask for `DEFAULT_STORAGE_ROOT`. Instead it creates a  `STORAGE_ROOT` depending on `functions.sh`.

So if you don't want to let users change their storage dir, then you needn't update / move the old config to /tmp and source it.

I would very appreciated it if advanced user could move / change the storage dir.

*Update*
Sry I haven't seen this one #106

### PR DESCRIPTION
**Pull request by h8h**
What I've tested so far:
Install miab (the default way).
Changed the STORAGE_USER and STORAGE_ROOT in the config file and start `mailinabox` again.
Removed the config file and start `mailinabox` again.

Everything seems to work fine. I can solely rely on a VM to test the PR, above I'm not able to test sending and receiving mails.

```bash
# Create the STORAGE_USER if it not exists
if [ ! $(id -u $STORAGE_USER >/dev/null 2>&1;) ]; then
  useradd -m $STORAGE_USER
fi
```

The intention of this part is to create the non-existing user even when the directory already exists. Ok I don't know why somebody wants to do that. But things can happen ...

Furthermore I think this condition ``if [ -z "$STORAGE_ROOT" ];`` is now unnecessary, because STORAGE_ROOT has not been set before.

### CODE REVIEW

**Comment by JoshData** [comment]
The idea behind the `-z` is that STORAGE_ROOT/USER might be set prior to running setup for the first time. So it may be set, but by the parent process. This might occur in an automated deploy situation where the user knows he wants STORAGE_ROOT set in a particular way from the start.

You also moved some of the migration stuff. The part you moved should only occur if the directory is being created. If the directory already exists, the migration version number shouldn't be written out because the directory might already have data from an earlier version of Mail-in-a-Box. I think there's a gap in my logic (directory exists but mailinabox.conf doesn't => migrations aren't run), but that should be fixed separately.

So these two things need to be fixed.

**Comment by h8h** [comment]
Which one has the higher priority? The one which might be set prior or the existing conf setting DEFAULT_STORAGE_ROOT?

**Comment by JoshData** [comment]
I'd be ok with either priority, but ideally anything set prior to running the script should override the configuration file. One day it might even move the directory for the user.

**Comment by h8h** [comment]
I hope I got you right :)

**Comment by JoshData** [comment]
Looks good. I'll test it later. Thanks! I may squash the two commits into one before merging tho.

**Comment by h8h** [comment]
Alright. Thank you!

**Comment by JoshData** [comment]
I don't think

    if [ ! $(id -u $STORAGE_USER >/dev/null 2>&1;) ]; then

is working. I think the `[ ! ...` test is checking the output of the `$(...)` subshell, which is always empty because of the redirection. This can be simplified to:

    if ! id -u $STORAGE_USER >/dev/null 2>&1; then

which checks the exit status of `id`, which seems to work.

**Comment by JoshData** [comment]
Merged!

**Pull request closed without merging**
