### PR TITLE
Create ufw_reset.sh

### PR DESCRIPTION
**Pull request by NitescuLucian**
I wonder if this would be required by others.

### CODE REVIEW

**Comment by yodax** [comment]
Ufw status is checked by the status checks. Rerunning the setup will reconfigure ufw.

I'm not sure the outlook settings are correct. Can you send mail to other hosts with these settings?

**Comment by NitescuLucian** [comment]
> Ufw status is checked by the status checks. Rerunning the setup will reconfigure ufw.

Would it not be to dangerous to run the setup again?

> I'm not sure the outlook settings are correct. Can you send mail to other hosts with these settings?

Yes I can. Pretty strange right?

**Comment by yodax** [comment]
> Would it not be to dangerous to run the setup again?

You can run it as many times as you like. 

> Yes I can. Pretty strange right?

It's not the submission port, but I'm not sure. It's not my area of expertise.

**Comment by NitescuLucian** [comment]
> You can run it as many times as you like.

Ok I added this script in order to restrict user (non-administrative) access to some configurations and folders.
How setup work? If I run it and I enter a new domain, would I add another domain to my server right? and a new admin in web platform? right? (or it would it replace my current settings.. witch would be even more worst). Correct me if I am not right! 🌝  
> It's not the submission port, but I'm not sure. It's not my area of expertise.

Let's wait with this then. I would also perform a MITM attack for the fun of it and I would respond with the results.

**Comment by yodax** [comment]
When rerunning the setup you don't need to enter anything new. When you add a domain you do that by adding a new email address or alias for that domain.

**Comment by NitescuLucian** [comment]
@yodax now I got it. Thank you for your assistance!

**Pull request closed without merging**
