### PR TITLE
Fix Boto

### PR DESCRIPTION
**Pull request by ponychicken**
Reverting changes introduced in b32cb6
We need to use the pypi version of boto, the other one doesn't work correctly with SIGv4 aws locations

### CODE REVIEW

**Comment by JoshData** [comment]
Thanks. Your reorg of the apt_install lines left `python-pip` in the wrong one.

**Comment by ponychicken** [comment]
Are you sure? According to the comment is just stuff for cryptography..

**Comment by JoshData** [comment]
The comment mentions the other packages on the line but not that one. (Also, it's for duplicity: https://github.com/ponychicken/mailinabox/commit/2e6c4103361e9924f90d6b22a11fdf3bb1c854b0#diff-b22bd340ceb479aa3cd1fe82de738343R7)

**Comment by ponychicken** [comment]
Can you fix it? I don't really understand which one you mean..

**Pull request closed without merging**
