### PR TITLE
Use tabs instead of spaces

### PR DESCRIPTION
**Pull request by 0pis**
Stay consitent with the rest of the file or do not mix spaces and tabs.

### CODE REVIEW

**Comment by ddavness** [comment]
im pretty sure that there are more than one file that might need to be re-indented

**Comment by JoshData** [comment]
The indentation still doesn't look right tho. The last bit is indented too much.

**Comment by 0pis** [comment]
I bet there are. Any suggestions, or just keep on adding to this?

> The indentation still doesn't look right tho. The last bit is indented too much.

I tried, but didn't get the right indent.

**Comment by 0pis** [comment]
Ok 'updated', sorry about that.

**Pull request merged**
