### PR TITLE
Sort custom dns table based on fqdn

### LINKED ISSUE #799: Sort Custom DNS Listing
Suggestion: Being able to sort the custom dns listings by domain name, instead of being sorted by the date/time they were created.

### PR DESCRIPTION
**Pull request by victorlap**
Fixes #799

An alternative would be to add something like http://js-grid.com/ (a lightweight datatables alternative), but I guess this PR should help a lot of people already.

### CODE REVIEW

**Comment by ctrl-i** [comment]
This is nice.

It would be even more useful in my opinion if each record type were also grouped.  For instance A records were listed alphabetically, then AAAA, then CNAME etc.

**Comment by victorlap** [comment]
@ctrl-i I think that would be better as well, but let's wait to see what Josh thinks of it.

**Comment by JoshData** [comment]
I agree. It should sort first by qname (the PR does that part correctly), and then for records that have the same qname, it should sort by record type. Thanks.

**Comment by victorlap** [comment]
I added the above suggestions.

Also when the record type and the domain are the same, it sorts on value, so for example `MX` records will have a logical order.

**Pull request merged**
