### PR TITLE
Fix for putty Line Drawing issues

### PR DESCRIPTION
**Pull request by c0h1b4**
Fix for putty (Windows) Line Drawing characters to be shown correctly.

### CODE REVIEW

**Comment by yodax** [comment]
I have tested this PR, still renders fine on a Mac terminal. 
schermafbeelding 2016-03-14 om 07 38 07

**Comment by JoshData** [comment]
Merging momentarily - thanks to you both!

**Comment by c0h1b4** [comment]
It works fine on mac. Issue is on windows putty.

**Comment by JoshData** [comment]
I think @yodax was just making sure this didn't cause a regression on other platforms.

**Comment by yodax** [comment]
Indeed was checking for regressions.

**Pull request merged**
