### PR TITLE
Update Z-Push to 2.3.6

### PR DESCRIPTION
**Pull request by yodax**
This is an update to the latest version of z-push. This is just a bug fix release. A few are interesting (at least to me)

- https://jira.z-hub.io/browse/ZP-1155 REVERT: [IMAP] iOS mail with z-push preview show raw html
- https://jira.z-hub.io/browse/ZP-1167 [IMAP] Some new messages are outdated and lost when sync

This was tested with iOS 10.

Full changelog:

```
Hi all,

we have just released Z-Push 2.3.6 (tag 2.3.6, commit ca1e816ee03c6c3ba4ed8d439ad7478b69f5404f).

This is a maintenence release without major features, but several important fixes. 
Thanks to our contributor Roel we got updated licenses for some pear classes used in the IMAP backend that will make it possible to get Z-Push into Debian.
Roel also contributed some man pages for the z-push CLI tools.
Yano contributed some other changes for the IMAP backend, improving the sync of messages.
Thanks guys! 
This version also contains a few fixes for the Kopano backend and KOE.

Changes since 2.3.5 final:

Tickets merged to final and released as 2.3.5+5 via repositories (also included in this version):
https://jira.z-hub.io/browse/ZP-1155 REVERT: [IMAP] iOS mail with z-push preview show raw html
https://jira.z-hub.io/browse/ZP-1179 folderid not mapped when deleting
https://jira.z-hub.io/browse/ZP-1191 Z-Push 2.3.5 breaks CentOS updates / libawl invalid dependency

Improvements
https://jira.z-hub.io/browse/ZP-1135 Update licenses of forked PEAR classes to be compatible with Debian (includes ZP-1152, ZP-1187, ZP-1189, ZP-1193) (thanks to Roel for achieving this!)
https://jira.z-hub.io/browse/ZP-1168 Log wait time in INFO level
https://jira.z-hub.io/browse/ZP-1178 Use PR_SEARCH_KEY in cases the GAB entry of a recipient is not available
https://jira.z-hub.io/browse/ZP-1190 Missing manpages for installed binaries (thanks to Roel for contributing)
https://jira.z-hub.io/browse/ZP-1195 Expose WebserviceDevice->GetDeviceDetails() for a single device

Bugs
https://jira.z-hub.io/browse/ZP-1163 Warning when install z-push-common on a new system
https://jira.z-hub.io/browse/ZP-1167 [IMAP] Some new messages are outdated and lost when sync
https://jira.z-hub.io/browse/ZP-1169 Kopano MAPI_E_UNCONFIGURED (0x8004011C) causes a folder resync
https://jira.z-hub.io/browse/ZP-1172 [IMAP] Some mails bodies or headers in Japanese may be decoded in wrong encoding
https://jira.z-hub.io/browse/ZP-1180 Implement plain streams for CalDav and CardDav backends
https://jira.z-hub.io/browse/ZP-1182 WARN messages doesn't log into z-push-error.log
https://jira.z-hub.io/browse/ZP-1185 Messages in error log are duplicated
https://jira.z-hub.io/browse/ZP-1186 Folder created under root in Outlook is not synced
https://jira.z-hub.io/browse/ZP-1188 Check if OOF expired and disabled it if needed


Code changes since Z-Push 2.3.5: https://stash.z-hub.io/projects/ZP/repos/z-push/compare/diff?targetBranch=refs%2Ftags%2F2.3.5&sourceBranch=refs%2Ftags%2F2.3.6

Install Z-Push 2.3.6 from the final repositories (recommended): https://wiki.z-hub.io/display/ZP/Installation

The tarball is available here (not recommended): http://download.z-push.org/final/2.3/z-push-2.3.6.tar.gz

Please share your experiences and give feedback!

Greetings,
Sebastian
Z-Push dev team
```

### CODE REVIEW

**Comment by nstanke** [comment]
This PR (bump to .6) introduced the iOS html preview bug  (ZP-1155) again for me. After a rollback to version 2.3.5 (And a reboot of the corresponding iOS 10.3.2 device) everything works as expected again.

@yodax Can you reproduce this behaviour?  

1) https://jira.z-hub.io/browse/ZP-1155

**Comment by yodax** [comment]
I still have/had the problem in both versions. But not consistently. Messages loaded in the state store with the old version still render incorrectly, the newer version renders newly received email properly. My iOS version is 10.3.1.

**Comment by nstanke** [comment]
I'll try to dig more into this later today, but at the moment it seems that I get a much better result with version 2.3.5 than 2.3.6.

**Comment by yodax** [comment]
Maybe we should raise a bug on their lira?

**Comment by nstanke** [comment]
Probably a good idea, I would first try to understand the histroy of this bug and try and do some testing on a different device before before I raise an unnecessary issue though.

**Comment by yodax** [comment]
@nstanke Any news? For me the previews are working. Also I've got the "feeling" push is working more reliably than with the previous point release. Also with the previous release I saw https://jira.z-hub.io/browse/ZP-1167 a couple of times.

**Comment by hachre** [comment]
My previews are broken and I have not been able to figure out what causes it. I also have extensive problems in Outlook 2016 on Windows 10. It has been syncing for days and still isn't nearly finished. I have 140,000 mails and set it up to sync everything. There's lots of messages in the zpush log saying that message loops have been detected.

**Comment by yodax** [comment]
Sometimes there are messages that can't be synced. I have one stored to log a bug report, but I haven't gotten around to it. I use it just on my mobile for push email on iOS. For the desktop I would stick with imap. 

It takes quite a powerful machine to host zpush I found. The new version together with php 7 (now in master) is a bit faster. 

For specific issues I think it would be best if we provide bug reports with as much detail as we can to zpush. Most of these issues have nothing to do with miab it self. 

When I find some time I will try to create a report for my broken message. You can try and find your emails that cause message loops. Just copy the raw email from the message store and try to log a bug report.

**Comment by hachre** [comment]
I reinstalled my Office 365 and realized my errors are endless floods of
```
ZPushAdmin::GetDeviceDetails(): device '42a34543cd644e85b590ef976a0df0e9' of user 'hachre@example.com' has invalid states. Please sync to solve this issue.
```
I have tried running `z-push-admin -u ... -d ... -a fixstates`, it only allows a few more hundred mails to sync before hanging up with the same error again flooding the log. Do you not see any of this at all in your case, @yodax?

**Comment by yodax** [comment]
> Do you not see any of this at all in your case, @yodax?

I've had one such message in the last couple of months. I don't use Office 365, just iOS. (I've tested this PR with office and mail for windows 10) There should be messages missing in the client, which are present in webmail. If you look for the message in your mail directory (grep for some content) than you could log an issue with z-push for that message.

What i've found in the past is that certain MIME types mess it up. Besides fixstates you could force a resync and purge all the states, but I wouldn't hold my breath. Z-push is always very brittle and error prone. Tough it has gotten a lot better over the past year.

**Comment by hachre** [comment]
I've figured it out. It was a client-side issue. Even removing the account from Outlook completely and adding it anew didn't fix it. In the end I had to manually remove a bunch of Outlook cache files from the Windows User's profile to get it working. It now works great. I'm leaving this here for anyone who might come across this in the future.

The files I had to delete were located in `%localappdata%\Microsoft\Outlook`. I deleted the entire `EasCache` and `RoamCache` folders as well as the leftover `.ost` files. If you are fine with your Outlook losing everything you probably can delete everything in this folder.

After deleting those files, I deleted the Outlook registration from Mail-in-a-Box Z-Push via `z-push-admin -u mymail@example.com -d ID -a remove` and then launched Outlook and added my mail account again. After all of this it finally started working and has been working great for the past few days so far!

Also refer to this https://github.com/mail-in-a-box/mailinabox/issues/1196#issuecomment-317638450 for information on how to get around Autodiscovery issues with the latest Outlook version.

**Pull request merged**
