### PR TITLE
[Issue #1159] Remove any +tag name in email alias before checking privileges

### PR DESCRIPTION
**Pull request by macmedia**
Issue #1159

### CODE REVIEW

**Comment by JoshData** [comment]
The change has to be a few lines lower or it won't work for IDNA domains.

**Comment by macmedia** [comment]
Thank you for feedback. What IDNA section are you referring to? This is just for the `get_mail_user_privileges()` function to check for administrator privileges. I don't see other calls to that function that this applies to. Im not changing the email var just adding the privileged_email var.

**Comment by JoshData** [comment]
Try making an alias from hostmaster@ツ.email to (a user) postmaster@ツ.email and see if it works.

**Comment by macmedia** [comment]
I guess I misunderstood the original issue. I thought the OP was having a problem authenticating his alias because the db query was checking the alias name with sysadmin+abuse@mybox.net and not the admin name of sysadmin@mybox.net.  I was just removing the +tag portion. Not checking if it was syntactically valid.

**Comment by JoshData** [comment]
That's all true. But I'm saying I don't think you did it right, and you should try the test case I suggested so you can see where I think it will go wrong.

**Comment by macmedia** [comment]
Sorry Josh, Im just not following. Im sure what I have is wrong! I just don't understand the end objective. Like I mentioned above, I just totally missed what the OP was requesting. 

I did try your test case and got the same results on v0.22 and the PR I did. Both seem to create alias to the account. Im clearly missing something. 

safari-type-email


v22-issue1159


I don't want to waste more of your time so I will just close this PR and let someone else tackle it.

**Comment by JoshData** [comment]
> I just don't understand the end objective. Like I mentioned above, I just totally missed what the OP was requesting.

You understand the end objective. I was concerned that your fix doesn't cover all cases though:

You changed the argument to `get_mail_user_privileges` so that it is no longer running through `sanitize_idn_email_address`. That means that if the target address has Unicode characters, it won't be found in the users table (because we only store ASCII equivalents in the users table) and so `get_mail_user_privileges` would always return as if the user did not exist. **That would make it impossible to make an alias for a domain control validation address that forwards to an administrator whose address is on an internationalized domain.**

I forgot that our users can only have ASCII characters now anyway, so this isn't an actual problem right now - it would be impossible to demonstrate that your change doesn't work now. But it could become an issue in the future. (My example that I asked you to try wasn't helpful anyway (for a different reason --- the `if` statement that checks DCV addresses allows any address that is also a DCV address so that's why it worked for you above).)

So because this _could_ be a problem in the future, we should still revise the PR. The line `privileged_email = ...` should occur immediately before the `if` statement that checks the DCV address so that it occurs _after_ `email` is updated by sanitize_idn_email_address.

**Comment by yodax** [comment]
Before the change:
schermafbeelding 2017-07-15 om 19 43 48

After:
schermafbeelding 2017-07-15 om 19 41 03

I move the stripping of the tags after the email sanitation.

**Comment by JoshData** [comment]
Great, thanks!

**Comment by JoshData** [comment]
Merged. Thanks everyone!

**Pull request merged**
