### PR TITLE
Local dns config

### PR DESCRIPTION
**Pull request by drpixie**
Hi Josh, 
As discussed, here's a pull request for my trivial NSD config change that permits additional local NSD config. I've tested it (using "sudo mailinabox") as initial setup and as subsequent reinstall, with no obvious problems. Thanks.

### CODE REVIEW

**Comment by JoshData** [comment]
I think

    include: "/etc/nsd/nsd.conf.d/*.conf"

would actually be nicer. This is probably in the stock nsd.conf that we are overwriting.

Could you test this instead and check that it works?

**Comment by drpixie** [comment]
Hi,

I agree, "include *.conf" would be nicer, but it fails because nsd.conf
includes itself and things go round in circles until nsd falls over :(
We could rename the all the include files, or nsd.conf, but I was trying to
keep it to minimal changes.

   Andrew.

**Comment by myfirstnameispaul** [comment]
That seems odd. On my installation `/etc/nsd/nsd.conf.d/` is empty.

**Comment by drpixie** [comment]
I wasn't putting the new include file in /etc/nsd/nsd.conf.d, just in
/etc/nsd, because the existing MIAB config file is in /etc/nsd.

It would make sense to move both the MIAB and local config files into
nsd.conf.d but that will involve modifying the stuff that generates & signs
the "box" domain config files, and I was trying to avoid wide-reaching
changes.

   Andrew.

**Comment by drpixie** [comment]
Josh, would you prefer a cleaner change with all the dns config files in nsd.conf.d? I'm happy to tweak management/dns_update.py and setup/dns.sh, and move the MIAB .conf into /etc/nsd/nsd.conf.

If yes, discard my PR and I'll make another PR.

**Comment by drpixie** [comment]
Better/cleaner PR coming. I'll close this one.

**Pull request closed without merging**
