### PR TITLE
Update Nextcloud to 12.0.2

### PR DESCRIPTION
**Pull request by yodax**
.1 and .2 are bug fix releases. This was tested by upgrading from 12 and all the way from 8.

### CODE REVIEW

**Comment by JoshData** [comment]
I actually tried this and had a problem - try upgrading to 12.0.0 and then upgrading to 12.0.2. The greps for version numbers broke.

**Comment by JoshData** [comment]
Actually, I just pushed a fix I had already been working on - 734745a.

**Comment by yodax** [comment]
Cool!

**Comment by yodax** [comment]
I tested your commit it works. I do wonder what actions I did to miss the failed upgrade... lucky you caught it.

**Pull request closed without merging**
